import type { GetStorefrontRentalOfferAvailabilityResponseDto as ApiGetStorefrontRentalOfferAvailabilityResponseDto } from '@repo/api-contracts';

export type GetStorefrontRentalOfferAvailabilityResponseDto = ApiGetStorefrontRentalOfferAvailabilityResponseDto;
