/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigningRouteImport } from './routes/signing'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiCustomerUploadRouteImport } from './routes/api/customer-upload'
import { Route as ApiBrandingUploadRouteImport } from './routes/api/branding-upload'
import { Route as PortalRegisterRouteImport } from './routes/_portal/register'
import { Route as PortalLoginRouteImport } from './routes/_portal/login'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AdminAdminRegisterRouteImport } from './routes/_admin/admin/register'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as PortalTenantRentalIndexRouteImport } from './routes/_portal/_tenant/rental/index'
import { Route as PortalTenantOrderCreatedWhatsappIndexRouteImport } from './routes/_portal/_tenant/order-created-whatsapp/index'
import { Route as PortalTenantOrderCreatedContactTeamIndexRouteImport } from './routes/_portal/_tenant/order-created-contact-team/index'
import { Route as PortalTenantOrderConfirmationIndexRouteImport } from './routes/_portal/_tenant/order-confirmation/index'
import { Route as PortalTenantOnboardIndexRouteImport } from './routes/_portal/_tenant/onboard/index'
import { Route as PortalTenantConfirmedRentalSuccessIndexRouteImport } from './routes/_portal/_tenant/confirmed-rental-success/index'
import { Route as PortalTenantCartIndexRouteImport } from './routes/_portal/_tenant/cart/index'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as AdminDashboardScheduleIndexRouteImport } from './routes/_admin/dashboard/schedule/index'
import { Route as AdminDashboardPromotionsIndexRouteImport } from './routes/_admin/dashboard/promotions/index'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/_admin/dashboard/orders/index'
import { Route as AdminDashboardLocationsIndexRouteImport } from './routes/_admin/dashboard/locations/index'
import { Route as AdminDashboardCustomersIndexRouteImport } from './routes/_admin/dashboard/customers/index'
import { Route as AdminDashboardCatalogIndexRouteImport } from './routes/_admin/dashboard/catalog/index'
import { Route as AdminDashboardCalendarIndexRouteImport } from './routes/_admin/dashboard/calendar/index'
import { Route as ApiOrdersOrderIdContractRouteImport } from './routes/api/orders/$orderId/contract'
import { Route as ApiOrdersOrderIdBudgetRouteImport } from './routes/api/orders/$orderId/budget'
import { Route as ApiDocumentSigningPublicUnsignedPdfRouteImport } from './routes/api/document-signing/public/unsigned-pdf'
import { Route as ApiDocumentSigningPublicSignedPdfRouteImport } from './routes/api/document-signing/public/signed-pdf'
import { Route as ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport } from './routes/api/customer-profiles/$customerProfileId/identity-document'
import { Route as PortalAuthGoogleFinalizeRouteImport } from './routes/_portal/auth/google/finalize'
import { Route as AdminDashboardPromotionsNewRouteImport } from './routes/_admin/dashboard/promotions/new'
import { Route as AdminDashboardOwnersOwnerIdRouteImport } from './routes/_admin/dashboard/owners/$ownerId'
import { Route as AdminDashboardOrdersNewRouteImport } from './routes/_admin/dashboard/orders/new'
import { Route as AdminDashboardLocationsNewRouteImport } from './routes/_admin/dashboard/locations/new'
import { Route as AdminDashboardLocationsLocationIdRouteImport } from './routes/_admin/dashboard/locations/$locationId'
import { Route as AdminDashboardCustomersCustomerIdRouteImport } from './routes/_admin/dashboard/customers/$customerId'
import { Route as AdminDashboardCatalogNewRouteImport } from './routes/_admin/dashboard/catalog/new'
import { Route as PortalTenantV2RentalIndexRouteImport } from './routes/_portal/_tenant/v2/rental/index'
import { Route as AdminDashboardOrdersPendingReviewIndexRouteImport } from './routes/_admin/dashboard/orders/pending-review/index'
import { Route as AdminDashboardOrdersOrderIdIndexRouteImport } from './routes/_admin/dashboard/orders/$orderId/index'
import { Route as AdminDashboardInventoryEquipmentTypesIndexRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/index'
import { Route as AdminDashboardInventoryAssetsIndexRouteImport } from './routes/_admin/dashboard/inventory/assets/index'
import { Route as AdminDashboardCustomersPendingProfilesIndexRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/index'
import { Route as AdminDashboardCatalogProductsIndexRouteImport } from './routes/_admin/dashboard/catalog/products/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogBundlesIndexRouteImport } from './routes/_admin/dashboard/catalog/bundles/index'
import { Route as AdminDashboardCatalogAccessoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/accessories/index'
import { Route as AdminDashboardCatalogRentableItemIdIndexRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/index'
import { Route as ApiOrdersOrderIdContractSignedRouteImport } from './routes/api/orders/$orderId/contract/signed'
import { Route as ApiOrdersOrderIdContractDownloadRouteImport } from './routes/api/orders/$orderId/contract/download'
import { Route as ApiOrdersOrderIdBudgetDownloadRouteImport } from './routes/api/orders/$orderId/budget/download'
import { Route as AdminDashboardPromotionsPromotionIdEditRouteImport } from './routes/_admin/dashboard/promotions/$promotionId/edit'
import { Route as AdminDashboardOrdersOrderIdEditRouteImport } from './routes/_admin/dashboard/orders/$orderId/edit'
import { Route as AdminDashboardLocationsBranchIdEditRouteImport } from './routes/_admin/dashboard/locations/$branchId/edit'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
import { Route as AdminDashboardCustomersPendingProfilesCustomerIdRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/$customerId'
import { Route as AdminDashboardCatalogProductsNewRouteImport } from './routes/_admin/dashboard/catalog/products/new'
import { Route as AdminDashboardCatalogPackagesNewRouteImport } from './routes/_admin/dashboard/catalog/packages/new'
import { Route as AdminDashboardCatalogBundlesNewRouteImport } from './routes/_admin/dashboard/catalog/bundles/new'
import { Route as AdminDashboardCatalogAccessoriesNewRouteImport } from './routes/_admin/dashboard/catalog/accessories/new'
import { Route as AdminDashboardCatalogProductsProductIdIndexRouteImport } from './routes/_admin/dashboard/catalog/products/$productId/index'
import { Route as AdminDashboardCatalogBundlesBundleIdIndexRouteImport } from './routes/_admin/dashboard/catalog/bundles/$bundleId/index'
import { Route as AdminDashboardCatalogAccessoriesAccessoryIdIndexRouteImport } from './routes/_admin/dashboard/catalog/accessories/$accessoryId/index'
import { Route as ApiOrdersOrderIdContractSignedDownloadRouteImport } from './routes/api/orders/$orderId/contract/signed/download'
import { Route as AdminDashboardCatalogProductsProductIdEditRouteImport } from './routes/_admin/dashboard/catalog/products/$productId/edit'
import { Route as AdminDashboardCatalogBundlesBundleIdEditRouteImport } from './routes/_admin/dashboard/catalog/bundles/$bundleId/edit'
import { Route as AdminDashboardCatalogAccessoriesAccessoryIdEditRouteImport } from './routes/_admin/dashboard/catalog/accessories/$accessoryId/edit'

const SigningRoute = SigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerUploadRoute = ApiCustomerUploadRouteImport.update({
  id: '/api/customer-upload',
  path: '/api/customer-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingUploadRoute = ApiBrandingUploadRouteImport.update({
  id: '/api/branding-upload',
  path: '/api/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRegisterRoute = AdminAdminRegisterRouteImport.update({
  id: '/_admin/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/_admin/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTenantRentalIndexRoute = PortalTenantRentalIndexRouteImport.update({
  id: '/_tenant/rental/',
  path: '/rental/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTenantOrderCreatedWhatsappIndexRoute =
  PortalTenantOrderCreatedWhatsappIndexRouteImport.update({
    id: '/_tenant/order-created-whatsapp/',
    path: '/order-created-whatsapp/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOrderCreatedContactTeamIndexRoute =
  PortalTenantOrderCreatedContactTeamIndexRouteImport.update({
    id: '/_tenant/order-created-contact-team/',
    path: '/order-created-contact-team/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOrderConfirmationIndexRoute =
  PortalTenantOrderConfirmationIndexRouteImport.update({
    id: '/_tenant/order-confirmation/',
    path: '/order-confirmation/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOnboardIndexRoute =
  PortalTenantOnboardIndexRouteImport.update({
    id: '/_tenant/onboard/',
    path: '/onboard/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantConfirmedRentalSuccessIndexRoute =
  PortalTenantConfirmedRentalSuccessIndexRouteImport.update({
    id: '/_tenant/confirmed-rental-success/',
    path: '/confirmed-rental-success/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantCartIndexRoute = PortalTenantCartIndexRouteImport.update({
  id: '/_tenant/cart/',
  path: '/cart/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardScheduleIndexRoute =
  AdminDashboardScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsIndexRoute =
  AdminDashboardPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsIndexRoute =
  AdminDashboardLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersIndexRoute =
  AdminDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogIndexRoute =
  AdminDashboardCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCalendarIndexRoute =
  AdminDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractRoute =
  ApiOrdersOrderIdContractRouteImport.update({
    id: '/api/orders/$orderId/contract',
    path: '/api/orders/$orderId/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersOrderIdBudgetRoute = ApiOrdersOrderIdBudgetRouteImport.update({
  id: '/api/orders/$orderId/budget',
  path: '/api/orders/$orderId/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentSigningPublicUnsignedPdfRoute =
  ApiDocumentSigningPublicUnsignedPdfRouteImport.update({
    id: '/api/document-signing/public/unsigned-pdf',
    path: '/api/document-signing/public/unsigned-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentSigningPublicSignedPdfRoute =
  ApiDocumentSigningPublicSignedPdfRouteImport.update({
    id: '/api/document-signing/public/signed-pdf',
    path: '/api/document-signing/public/signed-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute =
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport.update({
    id: '/api/customer-profiles/$customerProfileId/identity-document',
    path: '/api/customer-profiles/$customerProfileId/identity-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalAuthGoogleFinalizeRoute =
  PortalAuthGoogleFinalizeRouteImport.update({
    id: '/auth/google/finalize',
    path: '/auth/google/finalize',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const AdminDashboardPromotionsNewRoute =
  AdminDashboardPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersOwnerIdRoute =
  AdminDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersNewRoute = AdminDashboardOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardLocationsNewRoute =
  AdminDashboardLocationsNewRouteImport.update({
    id: '/locations/new',
    path: '/locations/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsLocationIdRoute =
  AdminDashboardLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersCustomerIdRoute =
  AdminDashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogNewRoute =
  AdminDashboardCatalogNewRouteImport.update({
    id: '/catalog/new',
    path: '/catalog/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const PortalTenantV2RentalIndexRoute =
  PortalTenantV2RentalIndexRouteImport.update({
    id: '/_tenant/v2/rental/',
    path: '/v2/rental/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const AdminDashboardOrdersPendingReviewIndexRoute =
  AdminDashboardOrdersPendingReviewIndexRouteImport.update({
    id: '/orders/pending-review/',
    path: '/orders/pending-review/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdIndexRoute =
  AdminDashboardOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesIndexRoute =
  AdminDashboardInventoryEquipmentTypesIndexRouteImport.update({
    id: '/inventory/equipment-types/',
    path: '/inventory/equipment-types/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryAssetsIndexRoute =
  AdminDashboardInventoryAssetsIndexRouteImport.update({
    id: '/inventory/assets/',
    path: '/inventory/assets/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesIndexRoute =
  AdminDashboardCustomersPendingProfilesIndexRouteImport.update({
    id: '/customers/pending-profiles/',
    path: '/customers/pending-profiles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsIndexRoute =
  AdminDashboardCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesIndexRoute =
  AdminDashboardCatalogBundlesIndexRouteImport.update({
    id: '/catalog/bundles/',
    path: '/catalog/bundles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogAccessoriesIndexRoute =
  AdminDashboardCatalogAccessoriesIndexRouteImport.update({
    id: '/catalog/accessories/',
    path: '/catalog/accessories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdIndexRoute =
  AdminDashboardCatalogRentableItemIdIndexRouteImport.update({
    id: '/catalog/$rentableItemId/',
    path: '/catalog/$rentableItemId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractSignedRoute =
  ApiOrdersOrderIdContractSignedRouteImport.update({
    id: '/signed',
    path: '/signed',
    getParentRoute: () => ApiOrdersOrderIdContractRoute,
  } as any)
const ApiOrdersOrderIdContractDownloadRoute =
  ApiOrdersOrderIdContractDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdContractRoute,
  } as any)
const ApiOrdersOrderIdBudgetDownloadRoute =
  ApiOrdersOrderIdBudgetDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdBudgetRoute,
  } as any)
const AdminDashboardPromotionsPromotionIdEditRoute =
  AdminDashboardPromotionsPromotionIdEditRouteImport.update({
    id: '/promotions/$promotionId/edit',
    path: '/promotions/$promotionId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdEditRoute =
  AdminDashboardOrdersOrderIdEditRouteImport.update({
    id: '/orders/$orderId/edit',
    path: '/orders/$orderId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardLocationsBranchIdEditRoute =
  AdminDashboardLocationsBranchIdEditRouteImport.update({
    id: '/locations/$branchId/edit',
    path: '/locations/$branchId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport.update({
    id: '/inventory/equipment-types/$equipmentTypeId',
    path: '/inventory/equipment-types/$equipmentTypeId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesCustomerIdRoute =
  AdminDashboardCustomersPendingProfilesCustomerIdRouteImport.update({
    id: '/customers/pending-profiles/$customerId',
    path: '/customers/pending-profiles/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsNewRoute =
  AdminDashboardCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesNewRoute =
  AdminDashboardCatalogPackagesNewRouteImport.update({
    id: '/catalog/packages/new',
    path: '/catalog/packages/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesNewRoute =
  AdminDashboardCatalogBundlesNewRouteImport.update({
    id: '/catalog/bundles/new',
    path: '/catalog/bundles/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogAccessoriesNewRoute =
  AdminDashboardCatalogAccessoriesNewRouteImport.update({
    id: '/catalog/accessories/new',
    path: '/catalog/accessories/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogProductsProductIdIndexRoute =
  AdminDashboardCatalogProductsProductIdIndexRouteImport.update({
    id: '/catalog/products/$productId/',
    path: '/catalog/products/$productId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesBundleIdIndexRoute =
  AdminDashboardCatalogBundlesBundleIdIndexRouteImport.update({
    id: '/catalog/bundles/$bundleId/',
    path: '/catalog/bundles/$bundleId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute =
  AdminDashboardCatalogAccessoriesAccessoryIdIndexRouteImport.update({
    id: '/catalog/accessories/$accessoryId/',
    path: '/catalog/accessories/$accessoryId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractSignedDownloadRoute =
  ApiOrdersOrderIdContractSignedDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdContractSignedRoute,
  } as any)
const AdminDashboardCatalogProductsProductIdEditRoute =
  AdminDashboardCatalogProductsProductIdEditRouteImport.update({
    id: '/catalog/products/$productId/edit',
    path: '/catalog/products/$productId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogBundlesBundleIdEditRoute =
  AdminDashboardCatalogBundlesBundleIdEditRouteImport.update({
    id: '/catalog/bundles/$bundleId/edit',
    path: '/catalog/bundles/$bundleId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogAccessoriesAccessoryIdEditRoute =
  AdminDashboardCatalogAccessoriesAccessoryIdEditRouteImport.update({
    id: '/catalog/accessories/$accessoryId/edit',
    path: '/catalog/accessories/$accessoryId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signing': typeof SigningRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/login': typeof PortalLoginRoute
  '/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/dashboard/locations/new': typeof AdminDashboardLocationsNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/budget': typeof ApiOrdersOrderIdBudgetRouteWithChildren
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/cart/': typeof PortalTenantCartIndexRoute
  '/confirmed-rental-success/': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/onboard/': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/order-created-contact-team/': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/order-created-whatsapp/': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/rental/': typeof PortalTenantRentalIndexRoute
  '/dashboard/catalog/accessories/new': typeof AdminDashboardCatalogAccessoriesNewRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/locations/$branchId/edit': typeof AdminDashboardLocationsBranchIdEditRoute
  '/dashboard/orders/$orderId/edit': typeof AdminDashboardOrdersOrderIdEditRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/budget/download': typeof ApiOrdersOrderIdBudgetDownloadRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/accessories/': typeof AdminDashboardCatalogAccessoriesIndexRoute
  '/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
  '/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/dashboard/orders/pending-review/': typeof AdminDashboardOrdersPendingReviewIndexRoute
  '/v2/rental/': typeof PortalTenantV2RentalIndexRoute
  '/dashboard/catalog/accessories/$accessoryId/edit': typeof AdminDashboardCatalogAccessoriesAccessoryIdEditRoute
  '/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
  '/dashboard/catalog/accessories/$accessoryId/': typeof AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute
  '/dashboard/catalog/bundles/$bundleId/': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/dashboard/catalog/products/$productId/': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signing': typeof SigningRoute
  '/login': typeof PortalLoginRoute
  '/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/dashboard/locations/new': typeof AdminDashboardLocationsNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/budget': typeof ApiOrdersOrderIdBudgetRouteWithChildren
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/calendar': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/locations': typeof AdminDashboardLocationsIndexRoute
  '/dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/schedule': typeof AdminDashboardScheduleIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/cart': typeof PortalTenantCartIndexRoute
  '/confirmed-rental-success': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/onboard': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation': typeof PortalTenantOrderConfirmationIndexRoute
  '/order-created-contact-team': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/order-created-whatsapp': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/rental': typeof PortalTenantRentalIndexRoute
  '/dashboard/catalog/accessories/new': typeof AdminDashboardCatalogAccessoriesNewRoute
  '/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/locations/$branchId/edit': typeof AdminDashboardLocationsBranchIdEditRoute
  '/dashboard/orders/$orderId/edit': typeof AdminDashboardOrdersOrderIdEditRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/budget/download': typeof ApiOrdersOrderIdBudgetDownloadRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/dashboard/catalog/$rentableItemId': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/accessories': typeof AdminDashboardCatalogAccessoriesIndexRoute
  '/dashboard/catalog/bundles': typeof AdminDashboardCatalogBundlesIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/products': typeof AdminDashboardCatalogProductsIndexRoute
  '/dashboard/customers/pending-profiles': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/assets': typeof AdminDashboardInventoryAssetsIndexRoute
  '/dashboard/inventory/equipment-types': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/dashboard/orders/pending-review': typeof AdminDashboardOrdersPendingReviewIndexRoute
  '/v2/rental': typeof PortalTenantV2RentalIndexRoute
  '/dashboard/catalog/accessories/$accessoryId/edit': typeof AdminDashboardCatalogAccessoriesAccessoryIdEditRoute
  '/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
  '/dashboard/catalog/accessories/$accessoryId': typeof AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute
  '/dashboard/catalog/bundles/$bundleId': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/dashboard/catalog/products/$productId': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteRouteWithChildren
  '/signing': typeof SigningRoute
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/_portal/login': typeof PortalLoginRoute
  '/_portal/register': typeof PortalRegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/register': typeof AdminAdminRegisterRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/_admin/dashboard/customers/$customerId': typeof AdminDashboardCustomersCustomerIdRoute
  '/_admin/dashboard/locations/$locationId': typeof AdminDashboardLocationsLocationIdRoute
  '/_admin/dashboard/locations/new': typeof AdminDashboardLocationsNewRoute
  '/_admin/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/_admin/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/_admin/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/_portal/auth/google/finalize': typeof PortalAuthGoogleFinalizeRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/budget': typeof ApiOrdersOrderIdBudgetRouteWithChildren
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/_admin/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/_admin/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/_admin/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/_admin/dashboard/locations/': typeof AdminDashboardLocationsIndexRoute
  '/_admin/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/_admin/dashboard/schedule/': typeof AdminDashboardScheduleIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_portal/_tenant/cart/': typeof PortalTenantCartIndexRoute
  '/_portal/_tenant/confirmed-rental-success/': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/_portal/_tenant/onboard/': typeof PortalTenantOnboardIndexRoute
  '/_portal/_tenant/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/_portal/_tenant/order-created-contact-team/': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/_portal/_tenant/order-created-whatsapp/': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/_portal/_tenant/rental/': typeof PortalTenantRentalIndexRoute
  '/_admin/dashboard/catalog/accessories/new': typeof AdminDashboardCatalogAccessoriesNewRoute
  '/_admin/dashboard/catalog/bundles/new': typeof AdminDashboardCatalogBundlesNewRoute
  '/_admin/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/_admin/dashboard/catalog/products/new': typeof AdminDashboardCatalogProductsNewRoute
  '/_admin/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/_admin/dashboard/locations/$branchId/edit': typeof AdminDashboardLocationsBranchIdEditRoute
  '/_admin/dashboard/orders/$orderId/edit': typeof AdminDashboardOrdersOrderIdEditRoute
  '/_admin/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/budget/download': typeof ApiOrdersOrderIdBudgetDownloadRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/_admin/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/_admin/dashboard/catalog/accessories/': typeof AdminDashboardCatalogAccessoriesIndexRoute
  '/_admin/dashboard/catalog/bundles/': typeof AdminDashboardCatalogBundlesIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/catalog/products/': typeof AdminDashboardCatalogProductsIndexRoute
  '/_admin/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/_admin/dashboard/inventory/assets/': typeof AdminDashboardInventoryAssetsIndexRoute
  '/_admin/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/_admin/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/_admin/dashboard/orders/pending-review/': typeof AdminDashboardOrdersPendingReviewIndexRoute
  '/_portal/_tenant/v2/rental/': typeof PortalTenantV2RentalIndexRoute
  '/_admin/dashboard/catalog/accessories/$accessoryId/edit': typeof AdminDashboardCatalogAccessoriesAccessoryIdEditRoute
  '/_admin/dashboard/catalog/bundles/$bundleId/edit': typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  '/_admin/dashboard/catalog/products/$productId/edit': typeof AdminDashboardCatalogProductsProductIdEditRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
  '/_admin/dashboard/catalog/accessories/$accessoryId/': typeof AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute
  '/_admin/dashboard/catalog/bundles/$bundleId/': typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  '/_admin/dashboard/catalog/products/$productId/': typeof AdminDashboardCatalogProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signing'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dashboard/'
    | '/dashboard/catalog/new'
    | '/dashboard/customers/$customerId'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/budget'
    | '/api/orders/$orderId/contract'
    | '/dashboard/calendar/'
    | '/dashboard/catalog/'
    | '/dashboard/customers/'
    | '/dashboard/locations/'
    | '/dashboard/orders/'
    | '/dashboard/owners/'
    | '/dashboard/promotions/'
    | '/dashboard/schedule/'
    | '/dashboard/settings/'
    | '/cart/'
    | '/confirmed-rental-success/'
    | '/onboard/'
    | '/order-confirmation/'
    | '/order-created-contact-team/'
    | '/order-created-whatsapp/'
    | '/rental/'
    | '/dashboard/catalog/accessories/new'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/catalog/products/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/locations/$branchId/edit'
    | '/dashboard/orders/$orderId/edit'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/budget/download'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/dashboard/catalog/$rentableItemId/'
    | '/dashboard/catalog/accessories/'
    | '/dashboard/catalog/bundles/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/catalog/products/'
    | '/dashboard/customers/pending-profiles/'
    | '/dashboard/inventory/assets/'
    | '/dashboard/inventory/equipment-types/'
    | '/dashboard/orders/$orderId/'
    | '/dashboard/orders/pending-review/'
    | '/v2/rental/'
    | '/dashboard/catalog/accessories/$accessoryId/edit'
    | '/dashboard/catalog/bundles/$bundleId/edit'
    | '/dashboard/catalog/products/$productId/edit'
    | '/api/orders/$orderId/contract/signed/download'
    | '/dashboard/catalog/accessories/$accessoryId/'
    | '/dashboard/catalog/bundles/$bundleId/'
    | '/dashboard/catalog/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signing'
    | '/login'
    | '/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/admin/login'
    | '/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/dashboard'
    | '/dashboard/catalog/new'
    | '/dashboard/customers/$customerId'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/budget'
    | '/api/orders/$orderId/contract'
    | '/dashboard/calendar'
    | '/dashboard/catalog'
    | '/dashboard/customers'
    | '/dashboard/locations'
    | '/dashboard/orders'
    | '/dashboard/owners'
    | '/dashboard/promotions'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/cart'
    | '/confirmed-rental-success'
    | '/onboard'
    | '/order-confirmation'
    | '/order-created-contact-team'
    | '/order-created-whatsapp'
    | '/rental'
    | '/dashboard/catalog/accessories/new'
    | '/dashboard/catalog/bundles/new'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/catalog/products/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/locations/$branchId/edit'
    | '/dashboard/orders/$orderId/edit'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/budget/download'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/dashboard/catalog/$rentableItemId'
    | '/dashboard/catalog/accessories'
    | '/dashboard/catalog/bundles'
    | '/dashboard/catalog/categories'
    | '/dashboard/catalog/products'
    | '/dashboard/customers/pending-profiles'
    | '/dashboard/inventory/assets'
    | '/dashboard/inventory/equipment-types'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/pending-review'
    | '/v2/rental'
    | '/dashboard/catalog/accessories/$accessoryId/edit'
    | '/dashboard/catalog/bundles/$bundleId/edit'
    | '/dashboard/catalog/products/$productId/edit'
    | '/api/orders/$orderId/contract/signed/download'
    | '/dashboard/catalog/accessories/$accessoryId'
    | '/dashboard/catalog/bundles/$bundleId'
    | '/dashboard/catalog/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/signing'
    | '/_admin/dashboard'
    | '/_portal/login'
    | '/_portal/register'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/_admin/admin/login'
    | '/_admin/admin/register'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/catalog/new'
    | '/_admin/dashboard/customers/$customerId'
    | '/_admin/dashboard/locations/$locationId'
    | '/_admin/dashboard/locations/new'
    | '/_admin/dashboard/orders/new'
    | '/_admin/dashboard/owners/$ownerId'
    | '/_admin/dashboard/promotions/new'
    | '/_portal/auth/google/finalize'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/budget'
    | '/api/orders/$orderId/contract'
    | '/_admin/dashboard/calendar/'
    | '/_admin/dashboard/catalog/'
    | '/_admin/dashboard/customers/'
    | '/_admin/dashboard/locations/'
    | '/_admin/dashboard/orders/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/promotions/'
    | '/_admin/dashboard/schedule/'
    | '/_admin/dashboard/settings/'
    | '/_portal/_tenant/cart/'
    | '/_portal/_tenant/confirmed-rental-success/'
    | '/_portal/_tenant/onboard/'
    | '/_portal/_tenant/order-confirmation/'
    | '/_portal/_tenant/order-created-contact-team/'
    | '/_portal/_tenant/order-created-whatsapp/'
    | '/_portal/_tenant/rental/'
    | '/_admin/dashboard/catalog/accessories/new'
    | '/_admin/dashboard/catalog/bundles/new'
    | '/_admin/dashboard/catalog/packages/new'
    | '/_admin/dashboard/catalog/products/new'
    | '/_admin/dashboard/customers/pending-profiles/$customerId'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/_admin/dashboard/locations/$branchId/edit'
    | '/_admin/dashboard/orders/$orderId/edit'
    | '/_admin/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/budget/download'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/_admin/dashboard/catalog/$rentableItemId/'
    | '/_admin/dashboard/catalog/accessories/'
    | '/_admin/dashboard/catalog/bundles/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/catalog/products/'
    | '/_admin/dashboard/customers/pending-profiles/'
    | '/_admin/dashboard/inventory/assets/'
    | '/_admin/dashboard/inventory/equipment-types/'
    | '/_admin/dashboard/orders/$orderId/'
    | '/_admin/dashboard/orders/pending-review/'
    | '/_portal/_tenant/v2/rental/'
    | '/_admin/dashboard/catalog/accessories/$accessoryId/edit'
    | '/_admin/dashboard/catalog/bundles/$bundleId/edit'
    | '/_admin/dashboard/catalog/products/$productId/edit'
    | '/api/orders/$orderId/contract/signed/download'
    | '/_admin/dashboard/catalog/accessories/$accessoryId/'
    | '/_admin/dashboard/catalog/bundles/$bundleId/'
    | '/_admin/dashboard/catalog/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  SigningRoute: typeof SigningRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  ApiBrandingUploadRoute: typeof ApiBrandingUploadRoute
  ApiCustomerUploadRoute: typeof ApiCustomerUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminRegisterRoute: typeof AdminAdminRegisterRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  ApiDocumentSigningPublicSignedPdfRoute: typeof ApiDocumentSigningPublicSignedPdfRoute
  ApiDocumentSigningPublicUnsignedPdfRoute: typeof ApiDocumentSigningPublicUnsignedPdfRoute
  ApiOrdersOrderIdBudgetRoute: typeof ApiOrdersOrderIdBudgetRouteWithChildren
  ApiOrdersOrderIdContractRoute: typeof ApiOrdersOrderIdContractRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signing': {
      id: '/signing'
      path: '/signing'
      fullPath: '/signing'
      preLoaderRoute: typeof SigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-upload': {
      id: '/api/customer-upload'
      path: '/api/customer-upload'
      fullPath: '/api/customer-upload'
      preLoaderRoute: typeof ApiCustomerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding-upload': {
      id: '/api/branding-upload'
      path: '/api/branding-upload'
      fullPath: '/api/branding-upload'
      preLoaderRoute: typeof ApiBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/register': {
      id: '/_portal/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/login': {
      id: '/_portal/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/register': {
      id: '/_admin/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminAdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/_tenant/rental/': {
      id: '/_portal/_tenant/rental/'
      path: '/rental'
      fullPath: '/rental/'
      preLoaderRoute: typeof PortalTenantRentalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-created-whatsapp/': {
      id: '/_portal/_tenant/order-created-whatsapp/'
      path: '/order-created-whatsapp'
      fullPath: '/order-created-whatsapp/'
      preLoaderRoute: typeof PortalTenantOrderCreatedWhatsappIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-created-contact-team/': {
      id: '/_portal/_tenant/order-created-contact-team/'
      path: '/order-created-contact-team'
      fullPath: '/order-created-contact-team/'
      preLoaderRoute: typeof PortalTenantOrderCreatedContactTeamIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-confirmation/': {
      id: '/_portal/_tenant/order-confirmation/'
      path: '/order-confirmation'
      fullPath: '/order-confirmation/'
      preLoaderRoute: typeof PortalTenantOrderConfirmationIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/onboard/': {
      id: '/_portal/_tenant/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof PortalTenantOnboardIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/confirmed-rental-success/': {
      id: '/_portal/_tenant/confirmed-rental-success/'
      path: '/confirmed-rental-success'
      fullPath: '/confirmed-rental-success/'
      preLoaderRoute: typeof PortalTenantConfirmedRentalSuccessIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/cart/': {
      id: '/_portal/_tenant/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof PortalTenantCartIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/schedule/': {
      id: '/_admin/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule/'
      preLoaderRoute: typeof AdminDashboardScheduleIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/': {
      id: '/_admin/dashboard/promotions/'
      path: '/promotions'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof AdminDashboardPromotionsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/': {
      id: '/_admin/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/': {
      id: '/_admin/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof AdminDashboardLocationsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/': {
      id: '/_admin/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AdminDashboardCustomersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/': {
      id: '/_admin/dashboard/catalog/'
      path: '/catalog'
      fullPath: '/dashboard/catalog/'
      preLoaderRoute: typeof AdminDashboardCatalogIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/calendar/': {
      id: '/_admin/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof AdminDashboardCalendarIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract': {
      id: '/api/orders/$orderId/contract'
      path: '/api/orders/$orderId/contract'
      fullPath: '/api/orders/$orderId/contract'
      preLoaderRoute: typeof ApiOrdersOrderIdContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/budget': {
      id: '/api/orders/$orderId/budget'
      path: '/api/orders/$orderId/budget'
      fullPath: '/api/orders/$orderId/budget'
      preLoaderRoute: typeof ApiOrdersOrderIdBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-signing/public/unsigned-pdf': {
      id: '/api/document-signing/public/unsigned-pdf'
      path: '/api/document-signing/public/unsigned-pdf'
      fullPath: '/api/document-signing/public/unsigned-pdf'
      preLoaderRoute: typeof ApiDocumentSigningPublicUnsignedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-signing/public/signed-pdf': {
      id: '/api/document-signing/public/signed-pdf'
      path: '/api/document-signing/public/signed-pdf'
      fullPath: '/api/document-signing/public/signed-pdf'
      preLoaderRoute: typeof ApiDocumentSigningPublicSignedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-profiles/$customerProfileId/identity-document': {
      id: '/api/customer-profiles/$customerProfileId/identity-document'
      path: '/api/customer-profiles/$customerProfileId/identity-document'
      fullPath: '/api/customer-profiles/$customerProfileId/identity-document'
      preLoaderRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/auth/google/finalize': {
      id: '/_portal/auth/google/finalize'
      path: '/auth/google/finalize'
      fullPath: '/auth/google/finalize'
      preLoaderRoute: typeof PortalAuthGoogleFinalizeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard/promotions/new': {
      id: '/_admin/dashboard/promotions/new'
      path: '/promotions/new'
      fullPath: '/dashboard/promotions/new'
      preLoaderRoute: typeof AdminDashboardPromotionsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/$ownerId': {
      id: '/_admin/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/dashboard/owners/$ownerId'
      preLoaderRoute: typeof AdminDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/new': {
      id: '/_admin/dashboard/orders/new'
      path: '/orders/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof AdminDashboardOrdersNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/new': {
      id: '/_admin/dashboard/locations/new'
      path: '/locations/new'
      fullPath: '/dashboard/locations/new'
      preLoaderRoute: typeof AdminDashboardLocationsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/$locationId': {
      id: '/_admin/dashboard/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/dashboard/locations/$locationId'
      preLoaderRoute: typeof AdminDashboardLocationsLocationIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/$customerId': {
      id: '/_admin/dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/new': {
      id: '/_admin/dashboard/catalog/new'
      path: '/catalog/new'
      fullPath: '/dashboard/catalog/new'
      preLoaderRoute: typeof AdminDashboardCatalogNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_portal/_tenant/v2/rental/': {
      id: '/_portal/_tenant/v2/rental/'
      path: '/v2/rental'
      fullPath: '/v2/rental/'
      preLoaderRoute: typeof PortalTenantV2RentalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_admin/dashboard/orders/pending-review/': {
      id: '/_admin/dashboard/orders/pending-review/'
      path: '/orders/pending-review'
      fullPath: '/dashboard/orders/pending-review/'
      preLoaderRoute: typeof AdminDashboardOrdersPendingReviewIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId/': {
      id: '/_admin/dashboard/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/': {
      id: '/_admin/dashboard/inventory/equipment-types/'
      path: '/inventory/equipment-types'
      fullPath: '/dashboard/inventory/equipment-types/'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/assets/': {
      id: '/_admin/dashboard/inventory/assets/'
      path: '/inventory/assets'
      fullPath: '/dashboard/inventory/assets/'
      preLoaderRoute: typeof AdminDashboardInventoryAssetsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/': {
      id: '/_admin/dashboard/customers/pending-profiles/'
      path: '/customers/pending-profiles'
      fullPath: '/dashboard/customers/pending-profiles/'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/': {
      id: '/_admin/dashboard/catalog/products/'
      path: '/catalog/products'
      fullPath: '/dashboard/catalog/products/'
      preLoaderRoute: typeof AdminDashboardCatalogProductsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/': {
      id: '/_admin/dashboard/catalog/bundles/'
      path: '/catalog/bundles'
      fullPath: '/dashboard/catalog/bundles/'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/accessories/': {
      id: '/_admin/dashboard/catalog/accessories/'
      path: '/catalog/accessories'
      fullPath: '/dashboard/catalog/accessories/'
      preLoaderRoute: typeof AdminDashboardCatalogAccessoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/': {
      id: '/_admin/dashboard/catalog/$rentableItemId/'
      path: '/catalog/$rentableItemId'
      fullPath: '/dashboard/catalog/$rentableItemId/'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract/signed': {
      id: '/api/orders/$orderId/contract/signed'
      path: '/signed'
      fullPath: '/api/orders/$orderId/contract/signed'
      preLoaderRoute: typeof ApiOrdersOrderIdContractSignedRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractRoute
    }
    '/api/orders/$orderId/contract/download': {
      id: '/api/orders/$orderId/contract/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/contract/download'
      preLoaderRoute: typeof ApiOrdersOrderIdContractDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractRoute
    }
    '/api/orders/$orderId/budget/download': {
      id: '/api/orders/$orderId/budget/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/budget/download'
      preLoaderRoute: typeof ApiOrdersOrderIdBudgetDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdBudgetRoute
    }
    '/_admin/dashboard/promotions/$promotionId/edit': {
      id: '/_admin/dashboard/promotions/$promotionId/edit'
      path: '/promotions/$promotionId/edit'
      fullPath: '/dashboard/promotions/$promotionId/edit'
      preLoaderRoute: typeof AdminDashboardPromotionsPromotionIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId/edit': {
      id: '/_admin/dashboard/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/dashboard/orders/$orderId/edit'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/locations/$branchId/edit': {
      id: '/_admin/dashboard/locations/$branchId/edit'
      path: '/locations/$branchId/edit'
      fullPath: '/dashboard/locations/$branchId/edit'
      preLoaderRoute: typeof AdminDashboardLocationsBranchIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
      path: '/inventory/equipment-types/$equipmentTypeId'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/$customerId': {
      id: '/_admin/dashboard/customers/pending-profiles/$customerId'
      path: '/customers/pending-profiles/$customerId'
      fullPath: '/dashboard/customers/pending-profiles/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/new': {
      id: '/_admin/dashboard/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/dashboard/catalog/products/new'
      preLoaderRoute: typeof AdminDashboardCatalogProductsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/new': {
      id: '/_admin/dashboard/catalog/packages/new'
      path: '/catalog/packages/new'
      fullPath: '/dashboard/catalog/packages/new'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/new': {
      id: '/_admin/dashboard/catalog/bundles/new'
      path: '/catalog/bundles/new'
      fullPath: '/dashboard/catalog/bundles/new'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/accessories/new': {
      id: '/_admin/dashboard/catalog/accessories/new'
      path: '/catalog/accessories/new'
      fullPath: '/dashboard/catalog/accessories/new'
      preLoaderRoute: typeof AdminDashboardCatalogAccessoriesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/products/$productId/': {
      id: '/_admin/dashboard/catalog/products/$productId/'
      path: '/catalog/products/$productId'
      fullPath: '/dashboard/catalog/products/$productId/'
      preLoaderRoute: typeof AdminDashboardCatalogProductsProductIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/$bundleId/': {
      id: '/_admin/dashboard/catalog/bundles/$bundleId/'
      path: '/catalog/bundles/$bundleId'
      fullPath: '/dashboard/catalog/bundles/$bundleId/'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesBundleIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/accessories/$accessoryId/': {
      id: '/_admin/dashboard/catalog/accessories/$accessoryId/'
      path: '/catalog/accessories/$accessoryId'
      fullPath: '/dashboard/catalog/accessories/$accessoryId/'
      preLoaderRoute: typeof AdminDashboardCatalogAccessoriesAccessoryIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract/signed/download': {
      id: '/api/orders/$orderId/contract/signed/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/contract/signed/download'
      preLoaderRoute: typeof ApiOrdersOrderIdContractSignedDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractSignedRoute
    }
    '/_admin/dashboard/catalog/products/$productId/edit': {
      id: '/_admin/dashboard/catalog/products/$productId/edit'
      path: '/catalog/products/$productId/edit'
      fullPath: '/dashboard/catalog/products/$productId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogProductsProductIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/bundles/$bundleId/edit': {
      id: '/_admin/dashboard/catalog/bundles/$bundleId/edit'
      path: '/catalog/bundles/$bundleId/edit'
      fullPath: '/dashboard/catalog/bundles/$bundleId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogBundlesBundleIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/accessories/$accessoryId/edit': {
      id: '/_admin/dashboard/catalog/accessories/$accessoryId/edit'
      path: '/catalog/accessories/$accessoryId/edit'
      fullPath: '/dashboard/catalog/accessories/$accessoryId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogAccessoriesAccessoryIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalLoginRoute: typeof PortalLoginRoute
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalAuthGoogleFinalizeRoute: typeof PortalAuthGoogleFinalizeRoute
  PortalTenantCartIndexRoute: typeof PortalTenantCartIndexRoute
  PortalTenantConfirmedRentalSuccessIndexRoute: typeof PortalTenantConfirmedRentalSuccessIndexRoute
  PortalTenantOnboardIndexRoute: typeof PortalTenantOnboardIndexRoute
  PortalTenantOrderConfirmationIndexRoute: typeof PortalTenantOrderConfirmationIndexRoute
  PortalTenantOrderCreatedContactTeamIndexRoute: typeof PortalTenantOrderCreatedContactTeamIndexRoute
  PortalTenantOrderCreatedWhatsappIndexRoute: typeof PortalTenantOrderCreatedWhatsappIndexRoute
  PortalTenantRentalIndexRoute: typeof PortalTenantRentalIndexRoute
  PortalTenantV2RentalIndexRoute: typeof PortalTenantV2RentalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalLoginRoute: PortalLoginRoute,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalAuthGoogleFinalizeRoute: PortalAuthGoogleFinalizeRoute,
  PortalTenantCartIndexRoute: PortalTenantCartIndexRoute,
  PortalTenantConfirmedRentalSuccessIndexRoute:
    PortalTenantConfirmedRentalSuccessIndexRoute,
  PortalTenantOnboardIndexRoute: PortalTenantOnboardIndexRoute,
  PortalTenantOrderConfirmationIndexRoute:
    PortalTenantOrderConfirmationIndexRoute,
  PortalTenantOrderCreatedContactTeamIndexRoute:
    PortalTenantOrderCreatedContactTeamIndexRoute,
  PortalTenantOrderCreatedWhatsappIndexRoute:
    PortalTenantOrderCreatedWhatsappIndexRoute,
  PortalTenantRentalIndexRoute: PortalTenantRentalIndexRoute,
  PortalTenantV2RentalIndexRoute: PortalTenantV2RentalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardCatalogNewRoute: typeof AdminDashboardCatalogNewRoute
  AdminDashboardCustomersCustomerIdRoute: typeof AdminDashboardCustomersCustomerIdRoute
  AdminDashboardLocationsLocationIdRoute: typeof AdminDashboardLocationsLocationIdRoute
  AdminDashboardLocationsNewRoute: typeof AdminDashboardLocationsNewRoute
  AdminDashboardOrdersNewRoute: typeof AdminDashboardOrdersNewRoute
  AdminDashboardOwnersOwnerIdRoute: typeof AdminDashboardOwnersOwnerIdRoute
  AdminDashboardPromotionsNewRoute: typeof AdminDashboardPromotionsNewRoute
  AdminDashboardCalendarIndexRoute: typeof AdminDashboardCalendarIndexRoute
  AdminDashboardCatalogIndexRoute: typeof AdminDashboardCatalogIndexRoute
  AdminDashboardCustomersIndexRoute: typeof AdminDashboardCustomersIndexRoute
  AdminDashboardLocationsIndexRoute: typeof AdminDashboardLocationsIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardPromotionsIndexRoute: typeof AdminDashboardPromotionsIndexRoute
  AdminDashboardScheduleIndexRoute: typeof AdminDashboardScheduleIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardCatalogAccessoriesNewRoute: typeof AdminDashboardCatalogAccessoriesNewRoute
  AdminDashboardCatalogBundlesNewRoute: typeof AdminDashboardCatalogBundlesNewRoute
  AdminDashboardCatalogPackagesNewRoute: typeof AdminDashboardCatalogPackagesNewRoute
  AdminDashboardCatalogProductsNewRoute: typeof AdminDashboardCatalogProductsNewRoute
  AdminDashboardCustomersPendingProfilesCustomerIdRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  AdminDashboardLocationsBranchIdEditRoute: typeof AdminDashboardLocationsBranchIdEditRoute
  AdminDashboardOrdersOrderIdEditRoute: typeof AdminDashboardOrdersOrderIdEditRoute
  AdminDashboardPromotionsPromotionIdEditRoute: typeof AdminDashboardPromotionsPromotionIdEditRoute
  AdminDashboardCatalogRentableItemIdIndexRoute: typeof AdminDashboardCatalogRentableItemIdIndexRoute
  AdminDashboardCatalogAccessoriesIndexRoute: typeof AdminDashboardCatalogAccessoriesIndexRoute
  AdminDashboardCatalogBundlesIndexRoute: typeof AdminDashboardCatalogBundlesIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCatalogProductsIndexRoute: typeof AdminDashboardCatalogProductsIndexRoute
  AdminDashboardCustomersPendingProfilesIndexRoute: typeof AdminDashboardCustomersPendingProfilesIndexRoute
  AdminDashboardInventoryAssetsIndexRoute: typeof AdminDashboardInventoryAssetsIndexRoute
  AdminDashboardInventoryEquipmentTypesIndexRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  AdminDashboardOrdersOrderIdIndexRoute: typeof AdminDashboardOrdersOrderIdIndexRoute
  AdminDashboardOrdersPendingReviewIndexRoute: typeof AdminDashboardOrdersPendingReviewIndexRoute
  AdminDashboardCatalogAccessoriesAccessoryIdEditRoute: typeof AdminDashboardCatalogAccessoriesAccessoryIdEditRoute
  AdminDashboardCatalogBundlesBundleIdEditRoute: typeof AdminDashboardCatalogBundlesBundleIdEditRoute
  AdminDashboardCatalogProductsProductIdEditRoute: typeof AdminDashboardCatalogProductsProductIdEditRoute
  AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute: typeof AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute
  AdminDashboardCatalogBundlesBundleIdIndexRoute: typeof AdminDashboardCatalogBundlesBundleIdIndexRoute
  AdminDashboardCatalogProductsProductIdIndexRoute: typeof AdminDashboardCatalogProductsProductIdIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardCatalogNewRoute: AdminDashboardCatalogNewRoute,
  AdminDashboardCustomersCustomerIdRoute:
    AdminDashboardCustomersCustomerIdRoute,
  AdminDashboardLocationsLocationIdRoute:
    AdminDashboardLocationsLocationIdRoute,
  AdminDashboardLocationsNewRoute: AdminDashboardLocationsNewRoute,
  AdminDashboardOrdersNewRoute: AdminDashboardOrdersNewRoute,
  AdminDashboardOwnersOwnerIdRoute: AdminDashboardOwnersOwnerIdRoute,
  AdminDashboardPromotionsNewRoute: AdminDashboardPromotionsNewRoute,
  AdminDashboardCalendarIndexRoute: AdminDashboardCalendarIndexRoute,
  AdminDashboardCatalogIndexRoute: AdminDashboardCatalogIndexRoute,
  AdminDashboardCustomersIndexRoute: AdminDashboardCustomersIndexRoute,
  AdminDashboardLocationsIndexRoute: AdminDashboardLocationsIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardPromotionsIndexRoute: AdminDashboardPromotionsIndexRoute,
  AdminDashboardScheduleIndexRoute: AdminDashboardScheduleIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardCatalogAccessoriesNewRoute:
    AdminDashboardCatalogAccessoriesNewRoute,
  AdminDashboardCatalogBundlesNewRoute: AdminDashboardCatalogBundlesNewRoute,
  AdminDashboardCatalogPackagesNewRoute: AdminDashboardCatalogPackagesNewRoute,
  AdminDashboardCatalogProductsNewRoute: AdminDashboardCatalogProductsNewRoute,
  AdminDashboardCustomersPendingProfilesCustomerIdRoute:
    AdminDashboardCustomersPendingProfilesCustomerIdRoute,
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute:
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute,
  AdminDashboardLocationsBranchIdEditRoute:
    AdminDashboardLocationsBranchIdEditRoute,
  AdminDashboardOrdersOrderIdEditRoute: AdminDashboardOrdersOrderIdEditRoute,
  AdminDashboardPromotionsPromotionIdEditRoute:
    AdminDashboardPromotionsPromotionIdEditRoute,
  AdminDashboardCatalogRentableItemIdIndexRoute:
    AdminDashboardCatalogRentableItemIdIndexRoute,
  AdminDashboardCatalogAccessoriesIndexRoute:
    AdminDashboardCatalogAccessoriesIndexRoute,
  AdminDashboardCatalogBundlesIndexRoute:
    AdminDashboardCatalogBundlesIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCatalogProductsIndexRoute:
    AdminDashboardCatalogProductsIndexRoute,
  AdminDashboardCustomersPendingProfilesIndexRoute:
    AdminDashboardCustomersPendingProfilesIndexRoute,
  AdminDashboardInventoryAssetsIndexRoute:
    AdminDashboardInventoryAssetsIndexRoute,
  AdminDashboardInventoryEquipmentTypesIndexRoute:
    AdminDashboardInventoryEquipmentTypesIndexRoute,
  AdminDashboardOrdersOrderIdIndexRoute: AdminDashboardOrdersOrderIdIndexRoute,
  AdminDashboardOrdersPendingReviewIndexRoute:
    AdminDashboardOrdersPendingReviewIndexRoute,
  AdminDashboardCatalogAccessoriesAccessoryIdEditRoute:
    AdminDashboardCatalogAccessoriesAccessoryIdEditRoute,
  AdminDashboardCatalogBundlesBundleIdEditRoute:
    AdminDashboardCatalogBundlesBundleIdEditRoute,
  AdminDashboardCatalogProductsProductIdEditRoute:
    AdminDashboardCatalogProductsProductIdEditRoute,
  AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute:
    AdminDashboardCatalogAccessoriesAccessoryIdIndexRoute,
  AdminDashboardCatalogBundlesBundleIdIndexRoute:
    AdminDashboardCatalogBundlesBundleIdIndexRoute,
  AdminDashboardCatalogProductsProductIdIndexRoute:
    AdminDashboardCatalogProductsProductIdIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface ApiOrdersOrderIdBudgetRouteChildren {
  ApiOrdersOrderIdBudgetDownloadRoute: typeof ApiOrdersOrderIdBudgetDownloadRoute
}

const ApiOrdersOrderIdBudgetRouteChildren: ApiOrdersOrderIdBudgetRouteChildren =
  {
    ApiOrdersOrderIdBudgetDownloadRoute: ApiOrdersOrderIdBudgetDownloadRoute,
  }

const ApiOrdersOrderIdBudgetRouteWithChildren =
  ApiOrdersOrderIdBudgetRoute._addFileChildren(
    ApiOrdersOrderIdBudgetRouteChildren,
  )

interface ApiOrdersOrderIdContractSignedRouteChildren {
  ApiOrdersOrderIdContractSignedDownloadRoute: typeof ApiOrdersOrderIdContractSignedDownloadRoute
}

const ApiOrdersOrderIdContractSignedRouteChildren: ApiOrdersOrderIdContractSignedRouteChildren =
  {
    ApiOrdersOrderIdContractSignedDownloadRoute:
      ApiOrdersOrderIdContractSignedDownloadRoute,
  }

const ApiOrdersOrderIdContractSignedRouteWithChildren =
  ApiOrdersOrderIdContractSignedRoute._addFileChildren(
    ApiOrdersOrderIdContractSignedRouteChildren,
  )

interface ApiOrdersOrderIdContractRouteChildren {
  ApiOrdersOrderIdContractDownloadRoute: typeof ApiOrdersOrderIdContractDownloadRoute
  ApiOrdersOrderIdContractSignedRoute: typeof ApiOrdersOrderIdContractSignedRouteWithChildren
}

const ApiOrdersOrderIdContractRouteChildren: ApiOrdersOrderIdContractRouteChildren =
  {
    ApiOrdersOrderIdContractDownloadRoute:
      ApiOrdersOrderIdContractDownloadRoute,
    ApiOrdersOrderIdContractSignedRoute:
      ApiOrdersOrderIdContractSignedRouteWithChildren,
  }

const ApiOrdersOrderIdContractRouteWithChildren =
  ApiOrdersOrderIdContractRoute._addFileChildren(
    ApiOrdersOrderIdContractRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  SigningRoute: SigningRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  ApiBrandingUploadRoute: ApiBrandingUploadRoute,
  ApiCustomerUploadRoute: ApiCustomerUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminRegisterRoute: AdminAdminRegisterRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute:
    ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute,
  ApiDocumentSigningPublicSignedPdfRoute:
    ApiDocumentSigningPublicSignedPdfRoute,
  ApiDocumentSigningPublicUnsignedPdfRoute:
    ApiDocumentSigningPublicUnsignedPdfRoute,
  ApiOrdersOrderIdBudgetRoute: ApiOrdersOrderIdBudgetRouteWithChildren,
  ApiOrdersOrderIdContractRoute: ApiOrdersOrderIdContractRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
