export enum NotificationDispatchSkipReason {
  MUTED_BY_ENVIRONMENT = 'MUTED_BY_ENVIRONMENT',
  SUPPRESSED_BY_TENANT_COMMUNICATION_MODE = 'SUPPRESSED_BY_TENANT_COMMUNICATION_MODE',
  UNSUPPORTED_CHANNEL = 'UNSUPPORTED_CHANNEL',
}
