export enum NotificationType {
  RENTAL_CONFIRMED_CONFIRMATION = 'RENTAL_CONFIRMED_CONFIRMATION',
  RENTAL_CREATED_BY_CUSTOMER = 'RENTAL_CREATED_BY_CUSTOMER',
  RENTAL_CANCELLED = 'RENTAL_CANCELLED',
  DOCUMENT_SIGNING_INVITATION = 'DOCUMENT_SIGNING_INVITATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
}
