/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmedRentalSuccessRouteImport } from './routes/confirmed-rental-success'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SigningRouteImport } from './routes/signing'
import { Route as ApiCustomerUploadRouteImport } from './routes/api/customer-upload'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as PublicSigningSplatRouteImport } from './routes/public-signing/$'
import { Route as RentalIndexRouteImport } from './routes/rental/index'
import { Route as SessionSplatRouteImport } from './routes/session/$'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AuthGoogleFinalizeRouteImport } from './routes/auth/google/finalize'
import { Route as AuthGoogleStartRouteImport } from './routes/auth/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRentalSuccessRoute = ConfirmedRentalSuccessRouteImport.update({
  id: '/confirmed-rental-success',
  path: '/confirmed-rental-success',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningRoute = SigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerUploadRoute = ApiCustomerUploadRouteImport.update({
  id: '/api/customer-upload',
  path: '/api/customer-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSigningSplatRoute = PublicSigningSplatRouteImport.update({
  id: '/public-signing/$',
  path: '/public-signing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalIndexRoute = RentalIndexRouteImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSplatRoute = SessionSplatRouteImport.update({
  id: '/session/$',
  path: '/session/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleFinalizeRoute = AuthGoogleFinalizeRouteImport.update({
  id: '/auth/google/finalize',
  path: '/auth/google/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmed-rental-success': typeof ConfirmedRentalSuccessRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/signing': typeof SigningRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/public-signing/$': typeof PublicSigningSplatRoute
  '/session/$': typeof SessionSplatRoute
  '/cart/': typeof CartIndexRoute
  '/rental/': typeof RentalIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/finalize': typeof AuthGoogleFinalizeRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmed-rental-success': typeof ConfirmedRentalSuccessRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/signing': typeof SigningRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/public-signing/$': typeof PublicSigningSplatRoute
  '/session/$': typeof SessionSplatRoute
  '/cart': typeof CartIndexRoute
  '/rental': typeof RentalIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/finalize': typeof AuthGoogleFinalizeRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmed-rental-success': typeof ConfirmedRentalSuccessRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/signing': typeof SigningRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/public-signing/$': typeof PublicSigningSplatRoute
  '/session/$': typeof SessionSplatRoute
  '/cart/': typeof CartIndexRoute
  '/rental/': typeof RentalIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/finalize': typeof AuthGoogleFinalizeRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmed-rental-success'
    | '/health'
    | '/login'
    | '/onboard'
    | '/register'
    | '/signing'
    | '/api/customer-upload'
    | '/public-signing/$'
    | '/session/$'
    | '/cart/'
    | '/rental/'
    | '/auth/google/callback'
    | '/auth/google/finalize'
    | '/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmed-rental-success'
    | '/health'
    | '/login'
    | '/onboard'
    | '/register'
    | '/signing'
    | '/api/customer-upload'
    | '/public-signing/$'
    | '/session/$'
    | '/cart'
    | '/rental'
    | '/auth/google/callback'
    | '/auth/google/finalize'
    | '/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/confirmed-rental-success'
    | '/health'
    | '/login'
    | '/onboard'
    | '/register'
    | '/signing'
    | '/api/customer-upload'
    | '/public-signing/$'
    | '/session/$'
    | '/cart/'
    | '/rental/'
    | '/auth/google/callback'
    | '/auth/google/finalize'
    | '/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmedRentalSuccessRoute: typeof ConfirmedRentalSuccessRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  RegisterRoute: typeof RegisterRoute
  SigningRoute: typeof SigningRoute
  ApiCustomerUploadRoute: typeof ApiCustomerUploadRoute
  PublicSigningSplatRoute: typeof PublicSigningSplatRoute
  SessionSplatRoute: typeof SessionSplatRoute
  CartIndexRoute: typeof CartIndexRoute
  RentalIndexRoute: typeof RentalIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleFinalizeRoute: typeof AuthGoogleFinalizeRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed-rental-success': {
      id: '/confirmed-rental-success'
      path: '/confirmed-rental-success'
      fullPath: '/confirmed-rental-success'
      preLoaderRoute: typeof ConfirmedRentalSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing': {
      id: '/signing'
      path: '/signing'
      fullPath: '/signing'
      preLoaderRoute: typeof SigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-upload': {
      id: '/api/customer-upload'
      path: '/api/customer-upload'
      fullPath: '/api/customer-upload'
      preLoaderRoute: typeof ApiCustomerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-signing/$': {
      id: '/public-signing/$'
      path: '/public-signing/$'
      fullPath: '/public-signing/$'
      preLoaderRoute: typeof PublicSigningSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/': {
      id: '/rental/'
      path: '/rental'
      fullPath: '/rental/'
      preLoaderRoute: typeof RentalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$': {
      id: '/session/$'
      path: '/session/$'
      fullPath: '/session/$'
      preLoaderRoute: typeof SessionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/finalize': {
      id: '/auth/google/finalize'
      path: '/auth/google/finalize'
      fullPath: '/auth/google/finalize'
      preLoaderRoute: typeof AuthGoogleFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmedRentalSuccessRoute: ConfirmedRentalSuccessRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  RegisterRoute: RegisterRoute,
  SigningRoute: SigningRoute,
  ApiCustomerUploadRoute: ApiCustomerUploadRoute,
  PublicSigningSplatRoute: PublicSigningSplatRoute,
  SessionSplatRoute: SessionSplatRoute,
  CartIndexRoute: CartIndexRoute,
  RentalIndexRoute: RentalIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleFinalizeRoute: AuthGoogleFinalizeRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
