/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as SigningRouteImport } from './routes/signing'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as ApiBrandingUploadRouteImport } from './routes/api/branding-upload'
import { Route as ApiCustomerUploadRouteImport } from './routes/api/customer-upload'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as BackendSplatRouteImport } from './routes/backend/$'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as AdminAdminRegisterRouteImport } from './routes/_admin/admin/register'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AdminDashboardBranchesIndexRouteImport } from './routes/_admin/dashboard/branches/index'
import { Route as AdminDashboardBranchesNewRouteImport } from './routes/_admin/dashboard/branches/new'
import { Route as AdminDashboardCalendarIndexRouteImport } from './routes/_admin/dashboard/calendar/index'
import { Route as AdminDashboardCatalogIndexRouteImport } from './routes/_admin/dashboard/catalog/index'
import { Route as AdminDashboardCatalogNewRouteImport } from './routes/_admin/dashboard/catalog/new'
import { Route as AdminDashboardCustomersIndexRouteImport } from './routes/_admin/dashboard/customers/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/_admin/dashboard/orders/index'
import { Route as AdminDashboardOrdersNewRouteImport } from './routes/_admin/dashboard/orders/new'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardOwnersOwnerIdRouteImport } from './routes/_admin/dashboard/owners/$ownerId'
import { Route as AdminDashboardPromotionsIndexRouteImport } from './routes/_admin/dashboard/promotions/index'
import { Route as AdminDashboardPromotionsNewRouteImport } from './routes/_admin/dashboard/promotions/new'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as PortalTenantCartIndexRouteImport } from './routes/_portal/_tenant/cart/index'
import { Route as PortalTenantConfirmedRentalSuccessIndexRouteImport } from './routes/_portal/_tenant/confirmed-rental-success/index'
import { Route as PortalTenantOnboardIndexRouteImport } from './routes/_portal/_tenant/onboard/index'
import { Route as PortalTenantOrderConfirmationIndexRouteImport } from './routes/_portal/_tenant/order-confirmation/index'
import { Route as PortalTenantOrderCreatedContactTeamIndexRouteImport } from './routes/_portal/_tenant/order-created-contact-team/index'
import { Route as PortalTenantOrderCreatedWhatsappIndexRouteImport } from './routes/_portal/_tenant/order-created-whatsapp/index'
import { Route as PortalTenantRentalIndexRouteImport } from './routes/_portal/_tenant/rental/index'
import { Route as ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport } from './routes/api/customer-profiles/$customerProfileId/identity-document'
import { Route as ApiDocumentSigningPublicSignedPdfRouteImport } from './routes/api/document-signing/public/signed-pdf'
import { Route as ApiDocumentSigningPublicUnsignedPdfRouteImport } from './routes/api/document-signing/public/unsigned-pdf'
import { Route as ApiOrdersOrderIdContractRouteImport } from './routes/api/orders/$orderId/contract'
import { Route as AdminDashboardBranchesBranchIdEditRouteImport } from './routes/_admin/dashboard/branches/$branchId/edit'
import { Route as AdminDashboardCatalogRentableItemIdIndexRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogPackagesNewRouteImport } from './routes/_admin/dashboard/catalog/packages/new'
import { Route as AdminDashboardCustomersPendingProfilesIndexRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/index'
import { Route as AdminDashboardCustomersPendingProfilesCustomerIdRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/$customerId'
import { Route as AdminDashboardInventoryEquipmentTypesIndexRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/index'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
import { Route as AdminDashboardOrdersOrderIdIndexRouteImport } from './routes/_admin/dashboard/orders/$orderId/index'
import { Route as AdminDashboardPromotionsPromotionIdEditRouteImport } from './routes/_admin/dashboard/promotions/$promotionId/edit'
import { Route as ApiOrdersOrderIdContractDownloadRouteImport } from './routes/api/orders/$orderId/contract/download'
import { Route as ApiOrdersOrderIdContractSignedRouteImport } from './routes/api/orders/$orderId/contract/signed'
import { Route as ApiOrdersOrderIdContractSignedDownloadRouteImport } from './routes/api/orders/$orderId/contract/signed/download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningRoute = SigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiBrandingUploadRoute = ApiBrandingUploadRouteImport.update({
  id: '/api/branding-upload',
  path: '/api/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerUploadRoute = ApiCustomerUploadRouteImport.update({
  id: '/api/customer-upload',
  path: '/api/customer-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendSplatRoute = BackendSplatRouteImport.update({
  id: '/backend/$',
  path: '/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminRegisterRoute = AdminAdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardBranchesIndexRoute =
  AdminDashboardBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardBranchesNewRoute =
  AdminDashboardBranchesNewRouteImport.update({
    id: '/branches/new',
    path: '/branches/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCalendarIndexRoute =
  AdminDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogIndexRoute =
  AdminDashboardCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogNewRoute =
  AdminDashboardCatalogNewRouteImport.update({
    id: '/catalog/new',
    path: '/catalog/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersIndexRoute =
  AdminDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersNewRoute = AdminDashboardOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersOwnerIdRoute =
  AdminDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsIndexRoute =
  AdminDashboardPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsNewRoute =
  AdminDashboardPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const PortalTenantCartIndexRoute = PortalTenantCartIndexRouteImport.update({
  id: '/_tenant/cart/',
  path: '/cart/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTenantConfirmedRentalSuccessIndexRoute =
  PortalTenantConfirmedRentalSuccessIndexRouteImport.update({
    id: '/_tenant/confirmed-rental-success/',
    path: '/confirmed-rental-success/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOnboardIndexRoute =
  PortalTenantOnboardIndexRouteImport.update({
    id: '/_tenant/onboard/',
    path: '/onboard/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOrderConfirmationIndexRoute =
  PortalTenantOrderConfirmationIndexRouteImport.update({
    id: '/_tenant/order-confirmation/',
    path: '/order-confirmation/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOrderCreatedContactTeamIndexRoute =
  PortalTenantOrderCreatedContactTeamIndexRouteImport.update({
    id: '/_tenant/order-created-contact-team/',
    path: '/order-created-contact-team/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantOrderCreatedWhatsappIndexRoute =
  PortalTenantOrderCreatedWhatsappIndexRouteImport.update({
    id: '/_tenant/order-created-whatsapp/',
    path: '/order-created-whatsapp/',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalTenantRentalIndexRoute = PortalTenantRentalIndexRouteImport.update({
  id: '/_tenant/rental/',
  path: '/rental/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute =
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport.update({
    id: '/api/customer-profiles/$customerProfileId/identity-document',
    path: '/api/customer-profiles/$customerProfileId/identity-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentSigningPublicSignedPdfRoute =
  ApiDocumentSigningPublicSignedPdfRouteImport.update({
    id: '/api/document-signing/public/signed-pdf',
    path: '/api/document-signing/public/signed-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentSigningPublicUnsignedPdfRoute =
  ApiDocumentSigningPublicUnsignedPdfRouteImport.update({
    id: '/api/document-signing/public/unsigned-pdf',
    path: '/api/document-signing/public/unsigned-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersOrderIdContractRoute =
  ApiOrdersOrderIdContractRouteImport.update({
    id: '/api/orders/$orderId/contract',
    path: '/api/orders/$orderId/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardBranchesBranchIdEditRoute =
  AdminDashboardBranchesBranchIdEditRouteImport.update({
    id: '/branches/$branchId/edit',
    path: '/branches/$branchId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdIndexRoute =
  AdminDashboardCatalogRentableItemIdIndexRouteImport.update({
    id: '/catalog/$rentableItemId/',
    path: '/catalog/$rentableItemId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesNewRoute =
  AdminDashboardCatalogPackagesNewRouteImport.update({
    id: '/catalog/packages/new',
    path: '/catalog/packages/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesIndexRoute =
  AdminDashboardCustomersPendingProfilesIndexRouteImport.update({
    id: '/customers/pending-profiles/',
    path: '/customers/pending-profiles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesCustomerIdRoute =
  AdminDashboardCustomersPendingProfilesCustomerIdRouteImport.update({
    id: '/customers/pending-profiles/$customerId',
    path: '/customers/pending-profiles/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesIndexRoute =
  AdminDashboardInventoryEquipmentTypesIndexRouteImport.update({
    id: '/inventory/equipment-types/',
    path: '/inventory/equipment-types/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport.update({
    id: '/inventory/equipment-types/$equipmentTypeId',
    path: '/inventory/equipment-types/$equipmentTypeId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdIndexRoute =
  AdminDashboardOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsPromotionIdEditRoute =
  AdminDashboardPromotionsPromotionIdEditRouteImport.update({
    id: '/promotions/$promotionId/edit',
    path: '/promotions/$promotionId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiOrdersOrderIdContractDownloadRoute =
  ApiOrdersOrderIdContractDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdContractRoute,
  } as any)
const ApiOrdersOrderIdContractSignedRoute =
  ApiOrdersOrderIdContractSignedRouteImport.update({
    id: '/signed',
    path: '/signed',
    getParentRoute: () => ApiOrdersOrderIdContractRoute,
  } as any)
const ApiOrdersOrderIdContractSignedDownloadRoute =
  ApiOrdersOrderIdContractSignedDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiOrdersOrderIdContractSignedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signing': typeof SigningRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/branches/': typeof AdminDashboardBranchesIndexRoute
  '/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/cart/': typeof PortalTenantCartIndexRoute
  '/confirmed-rental-success/': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/onboard/': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/order-created-contact-team/': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/order-created-whatsapp/': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/rental/': typeof PortalTenantRentalIndexRoute
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signing': typeof SigningRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/dashboard/branches': typeof AdminDashboardBranchesIndexRoute
  '/dashboard/calendar': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/cart': typeof PortalTenantCartIndexRoute
  '/confirmed-rental-success': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/onboard': typeof PortalTenantOnboardIndexRoute
  '/order-confirmation': typeof PortalTenantOrderConfirmationIndexRoute
  '/order-created-contact-team': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/order-created-whatsapp': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/rental': typeof PortalTenantRentalIndexRoute
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/dashboard/catalog/$rentableItemId': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/customers/pending-profiles': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/signing': typeof SigningRoute
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/customer-upload': typeof ApiCustomerUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/register': typeof AdminAdminRegisterRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/_admin/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/_admin/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/_admin/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/_admin/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/api/document-signing/public/signed-pdf': typeof ApiDocumentSigningPublicSignedPdfRoute
  '/api/document-signing/public/unsigned-pdf': typeof ApiDocumentSigningPublicUnsignedPdfRoute
  '/api/orders/$orderId/contract': typeof ApiOrdersOrderIdContractRouteWithChildren
  '/_admin/dashboard/branches/': typeof AdminDashboardBranchesIndexRoute
  '/_admin/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/_admin/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/_admin/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/_admin/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_portal/_tenant/cart/': typeof PortalTenantCartIndexRoute
  '/_portal/_tenant/confirmed-rental-success/': typeof PortalTenantConfirmedRentalSuccessIndexRoute
  '/_portal/_tenant/onboard/': typeof PortalTenantOnboardIndexRoute
  '/_portal/_tenant/order-confirmation/': typeof PortalTenantOrderConfirmationIndexRoute
  '/_portal/_tenant/order-created-contact-team/': typeof PortalTenantOrderCreatedContactTeamIndexRoute
  '/_portal/_tenant/order-created-whatsapp/': typeof PortalTenantOrderCreatedWhatsappIndexRoute
  '/_portal/_tenant/rental/': typeof PortalTenantRentalIndexRoute
  '/_admin/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/_admin/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/_admin/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/_admin/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/api/orders/$orderId/contract/download': typeof ApiOrdersOrderIdContractDownloadRoute
  '/api/orders/$orderId/contract/signed': typeof ApiOrdersOrderIdContractSignedRouteWithChildren
  '/_admin/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/_admin/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/_admin/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/api/orders/$orderId/contract/signed/download': typeof ApiOrdersOrderIdContractSignedDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signing'
    | '/dashboard'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/backend/$'
    | '/admin/login'
    | '/admin/register'
    | '/dashboard/'
    | '/dashboard/branches/new'
    | '/dashboard/catalog/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/contract'
    | '/dashboard/branches/'
    | '/dashboard/calendar/'
    | '/dashboard/catalog/'
    | '/dashboard/customers/'
    | '/dashboard/orders/'
    | '/dashboard/owners/'
    | '/dashboard/promotions/'
    | '/dashboard/settings/'
    | '/cart/'
    | '/confirmed-rental-success/'
    | '/onboard/'
    | '/order-confirmation/'
    | '/order-created-contact-team/'
    | '/order-created-whatsapp/'
    | '/rental/'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/dashboard/catalog/$rentableItemId/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/customers/pending-profiles/'
    | '/dashboard/inventory/equipment-types/'
    | '/dashboard/orders/$orderId/'
    | '/api/orders/$orderId/contract/signed/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signing'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/backend/$'
    | '/admin/login'
    | '/admin/register'
    | '/dashboard'
    | '/dashboard/branches/new'
    | '/dashboard/catalog/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/contract'
    | '/dashboard/branches'
    | '/dashboard/calendar'
    | '/dashboard/catalog'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/owners'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/cart'
    | '/confirmed-rental-success'
    | '/onboard'
    | '/order-confirmation'
    | '/order-created-contact-team'
    | '/order-created-whatsapp'
    | '/rental'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/dashboard/catalog/$rentableItemId'
    | '/dashboard/catalog/categories'
    | '/dashboard/customers/pending-profiles'
    | '/dashboard/inventory/equipment-types'
    | '/dashboard/orders/$orderId'
    | '/api/orders/$orderId/contract/signed/download'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_portal'
    | '/signing'
    | '/_admin/dashboard'
    | '/api/branding-upload'
    | '/api/customer-upload'
    | '/api/upload'
    | '/backend/$'
    | '/_admin/admin/login'
    | '/_admin/admin/register'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/branches/new'
    | '/_admin/dashboard/catalog/new'
    | '/_admin/dashboard/orders/new'
    | '/_admin/dashboard/owners/$ownerId'
    | '/_admin/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/api/document-signing/public/signed-pdf'
    | '/api/document-signing/public/unsigned-pdf'
    | '/api/orders/$orderId/contract'
    | '/_admin/dashboard/branches/'
    | '/_admin/dashboard/calendar/'
    | '/_admin/dashboard/catalog/'
    | '/_admin/dashboard/customers/'
    | '/_admin/dashboard/orders/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/promotions/'
    | '/_admin/dashboard/settings/'
    | '/_portal/_tenant/cart/'
    | '/_portal/_tenant/confirmed-rental-success/'
    | '/_portal/_tenant/onboard/'
    | '/_portal/_tenant/order-confirmation/'
    | '/_portal/_tenant/order-created-contact-team/'
    | '/_portal/_tenant/order-created-whatsapp/'
    | '/_portal/_tenant/rental/'
    | '/_admin/dashboard/branches/$branchId/edit'
    | '/_admin/dashboard/catalog/packages/new'
    | '/_admin/dashboard/customers/pending-profiles/$customerId'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/_admin/dashboard/promotions/$promotionId/edit'
    | '/api/orders/$orderId/contract/download'
    | '/api/orders/$orderId/contract/signed'
    | '/_admin/dashboard/catalog/$rentableItemId/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/customers/pending-profiles/'
    | '/_admin/dashboard/inventory/equipment-types/'
    | '/_admin/dashboard/orders/$orderId/'
    | '/api/orders/$orderId/contract/signed/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  SigningRoute: typeof SigningRoute
  ApiBrandingUploadRoute: typeof ApiBrandingUploadRoute
  ApiCustomerUploadRoute: typeof ApiCustomerUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BackendSplatRoute: typeof BackendSplatRoute
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  ApiDocumentSigningPublicSignedPdfRoute: typeof ApiDocumentSigningPublicSignedPdfRoute
  ApiDocumentSigningPublicUnsignedPdfRoute: typeof ApiDocumentSigningPublicUnsignedPdfRoute
  ApiOrdersOrderIdContractRoute: typeof ApiOrdersOrderIdContractRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing': {
      id: '/signing'
      path: '/signing'
      fullPath: '/signing'
      preLoaderRoute: typeof SigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/branding-upload': {
      id: '/api/branding-upload'
      path: '/api/branding-upload'
      fullPath: '/api/branding-upload'
      preLoaderRoute: typeof ApiBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-upload': {
      id: '/api/customer-upload'
      path: '/api/customer-upload'
      fullPath: '/api/customer-upload'
      preLoaderRoute: typeof ApiCustomerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/$': {
      id: '/backend/$'
      path: '/backend/$'
      fullPath: '/backend/$'
      preLoaderRoute: typeof BackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/register': {
      id: '/_admin/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminAdminRegisterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/': {
      id: '/_admin/dashboard/branches/'
      path: '/branches'
      fullPath: '/dashboard/branches/'
      preLoaderRoute: typeof AdminDashboardBranchesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/new': {
      id: '/_admin/dashboard/branches/new'
      path: '/branches/new'
      fullPath: '/dashboard/branches/new'
      preLoaderRoute: typeof AdminDashboardBranchesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/calendar/': {
      id: '/_admin/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof AdminDashboardCalendarIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/': {
      id: '/_admin/dashboard/catalog/'
      path: '/catalog'
      fullPath: '/dashboard/catalog/'
      preLoaderRoute: typeof AdminDashboardCatalogIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/new': {
      id: '/_admin/dashboard/catalog/new'
      path: '/catalog/new'
      fullPath: '/dashboard/catalog/new'
      preLoaderRoute: typeof AdminDashboardCatalogNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/': {
      id: '/_admin/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AdminDashboardCustomersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/': {
      id: '/_admin/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/new': {
      id: '/_admin/dashboard/orders/new'
      path: '/orders/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof AdminDashboardOrdersNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/$ownerId': {
      id: '/_admin/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/dashboard/owners/$ownerId'
      preLoaderRoute: typeof AdminDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/': {
      id: '/_admin/dashboard/promotions/'
      path: '/promotions'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof AdminDashboardPromotionsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/new': {
      id: '/_admin/dashboard/promotions/new'
      path: '/promotions/new'
      fullPath: '/dashboard/promotions/new'
      preLoaderRoute: typeof AdminDashboardPromotionsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_portal/_tenant/cart/': {
      id: '/_portal/_tenant/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof PortalTenantCartIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/confirmed-rental-success/': {
      id: '/_portal/_tenant/confirmed-rental-success/'
      path: '/confirmed-rental-success'
      fullPath: '/confirmed-rental-success/'
      preLoaderRoute: typeof PortalTenantConfirmedRentalSuccessIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/onboard/': {
      id: '/_portal/_tenant/onboard/'
      path: '/onboard'
      fullPath: '/onboard/'
      preLoaderRoute: typeof PortalTenantOnboardIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-confirmation/': {
      id: '/_portal/_tenant/order-confirmation/'
      path: '/order-confirmation'
      fullPath: '/order-confirmation/'
      preLoaderRoute: typeof PortalTenantOrderConfirmationIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-created-contact-team/': {
      id: '/_portal/_tenant/order-created-contact-team/'
      path: '/order-created-contact-team'
      fullPath: '/order-created-contact-team/'
      preLoaderRoute: typeof PortalTenantOrderCreatedContactTeamIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/order-created-whatsapp/': {
      id: '/_portal/_tenant/order-created-whatsapp/'
      path: '/order-created-whatsapp'
      fullPath: '/order-created-whatsapp/'
      preLoaderRoute: typeof PortalTenantOrderCreatedWhatsappIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal/_tenant/rental/': {
      id: '/_portal/_tenant/rental/'
      path: '/rental'
      fullPath: '/rental/'
      preLoaderRoute: typeof PortalTenantRentalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/customer-profiles/$customerProfileId/identity-document': {
      id: '/api/customer-profiles/$customerProfileId/identity-document'
      path: '/api/customer-profiles/$customerProfileId/identity-document'
      fullPath: '/api/customer-profiles/$customerProfileId/identity-document'
      preLoaderRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-signing/public/signed-pdf': {
      id: '/api/document-signing/public/signed-pdf'
      path: '/api/document-signing/public/signed-pdf'
      fullPath: '/api/document-signing/public/signed-pdf'
      preLoaderRoute: typeof ApiDocumentSigningPublicSignedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-signing/public/unsigned-pdf': {
      id: '/api/document-signing/public/unsigned-pdf'
      path: '/api/document-signing/public/unsigned-pdf'
      fullPath: '/api/document-signing/public/unsigned-pdf'
      preLoaderRoute: typeof ApiDocumentSigningPublicUnsignedPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/contract': {
      id: '/api/orders/$orderId/contract'
      path: '/api/orders/$orderId/contract'
      fullPath: '/api/orders/$orderId/contract'
      preLoaderRoute: typeof ApiOrdersOrderIdContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/branches/$branchId/edit': {
      id: '/_admin/dashboard/branches/$branchId/edit'
      path: '/branches/$branchId/edit'
      fullPath: '/dashboard/branches/$branchId/edit'
      preLoaderRoute: typeof AdminDashboardBranchesBranchIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/': {
      id: '/_admin/dashboard/catalog/$rentableItemId/'
      path: '/catalog/$rentableItemId'
      fullPath: '/dashboard/catalog/$rentableItemId/'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/new': {
      id: '/_admin/dashboard/catalog/packages/new'
      path: '/catalog/packages/new'
      fullPath: '/dashboard/catalog/packages/new'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/': {
      id: '/_admin/dashboard/customers/pending-profiles/'
      path: '/customers/pending-profiles'
      fullPath: '/dashboard/customers/pending-profiles/'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/$customerId': {
      id: '/_admin/dashboard/customers/pending-profiles/$customerId'
      path: '/customers/pending-profiles/$customerId'
      fullPath: '/dashboard/customers/pending-profiles/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/': {
      id: '/_admin/dashboard/inventory/equipment-types/'
      path: '/inventory/equipment-types'
      fullPath: '/dashboard/inventory/equipment-types/'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
      path: '/inventory/equipment-types/$equipmentTypeId'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId/': {
      id: '/_admin/dashboard/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/$promotionId/edit': {
      id: '/_admin/dashboard/promotions/$promotionId/edit'
      path: '/promotions/$promotionId/edit'
      fullPath: '/dashboard/promotions/$promotionId/edit'
      preLoaderRoute: typeof AdminDashboardPromotionsPromotionIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/orders/$orderId/contract/download': {
      id: '/api/orders/$orderId/contract/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/contract/download'
      preLoaderRoute: typeof ApiOrdersOrderIdContractDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractRoute
    }
    '/api/orders/$orderId/contract/signed': {
      id: '/api/orders/$orderId/contract/signed'
      path: '/signed'
      fullPath: '/api/orders/$orderId/contract/signed'
      preLoaderRoute: typeof ApiOrdersOrderIdContractSignedRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractRoute
    }
    '/api/orders/$orderId/contract/signed/download': {
      id: '/api/orders/$orderId/contract/signed/download'
      path: '/download'
      fullPath: '/api/orders/$orderId/contract/signed/download'
      preLoaderRoute: typeof ApiOrdersOrderIdContractSignedDownloadRouteImport
      parentRoute: typeof ApiOrdersOrderIdContractSignedRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBranchesNewRoute: typeof AdminDashboardBranchesNewRoute
  AdminDashboardCatalogNewRoute: typeof AdminDashboardCatalogNewRoute
  AdminDashboardOrdersNewRoute: typeof AdminDashboardOrdersNewRoute
  AdminDashboardOwnersOwnerIdRoute: typeof AdminDashboardOwnersOwnerIdRoute
  AdminDashboardPromotionsNewRoute: typeof AdminDashboardPromotionsNewRoute
  AdminDashboardBranchesIndexRoute: typeof AdminDashboardBranchesIndexRoute
  AdminDashboardCalendarIndexRoute: typeof AdminDashboardCalendarIndexRoute
  AdminDashboardCatalogIndexRoute: typeof AdminDashboardCatalogIndexRoute
  AdminDashboardCustomersIndexRoute: typeof AdminDashboardCustomersIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardPromotionsIndexRoute: typeof AdminDashboardPromotionsIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardBranchesBranchIdEditRoute: typeof AdminDashboardBranchesBranchIdEditRoute
  AdminDashboardCatalogPackagesNewRoute: typeof AdminDashboardCatalogPackagesNewRoute
  AdminDashboardCustomersPendingProfilesCustomerIdRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  AdminDashboardPromotionsPromotionIdEditRoute: typeof AdminDashboardPromotionsPromotionIdEditRoute
  AdminDashboardCatalogRentableItemIdIndexRoute: typeof AdminDashboardCatalogRentableItemIdIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCustomersPendingProfilesIndexRoute: typeof AdminDashboardCustomersPendingProfilesIndexRoute
  AdminDashboardInventoryEquipmentTypesIndexRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  AdminDashboardOrdersOrderIdIndexRoute: typeof AdminDashboardOrdersOrderIdIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBranchesNewRoute: AdminDashboardBranchesNewRoute,
  AdminDashboardCatalogNewRoute: AdminDashboardCatalogNewRoute,
  AdminDashboardOrdersNewRoute: AdminDashboardOrdersNewRoute,
  AdminDashboardOwnersOwnerIdRoute: AdminDashboardOwnersOwnerIdRoute,
  AdminDashboardPromotionsNewRoute: AdminDashboardPromotionsNewRoute,
  AdminDashboardBranchesIndexRoute: AdminDashboardBranchesIndexRoute,
  AdminDashboardCalendarIndexRoute: AdminDashboardCalendarIndexRoute,
  AdminDashboardCatalogIndexRoute: AdminDashboardCatalogIndexRoute,
  AdminDashboardCustomersIndexRoute: AdminDashboardCustomersIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardPromotionsIndexRoute: AdminDashboardPromotionsIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardBranchesBranchIdEditRoute:
    AdminDashboardBranchesBranchIdEditRoute,
  AdminDashboardCatalogPackagesNewRoute: AdminDashboardCatalogPackagesNewRoute,
  AdminDashboardCustomersPendingProfilesCustomerIdRoute:
    AdminDashboardCustomersPendingProfilesCustomerIdRoute,
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute:
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute,
  AdminDashboardPromotionsPromotionIdEditRoute:
    AdminDashboardPromotionsPromotionIdEditRoute,
  AdminDashboardCatalogRentableItemIdIndexRoute:
    AdminDashboardCatalogRentableItemIdIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCustomersPendingProfilesIndexRoute:
    AdminDashboardCustomersPendingProfilesIndexRoute,
  AdminDashboardInventoryEquipmentTypesIndexRoute:
    AdminDashboardInventoryEquipmentTypesIndexRoute,
  AdminDashboardOrdersOrderIdIndexRoute: AdminDashboardOrdersOrderIdIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminRegisterRoute: typeof AdminAdminRegisterRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminRegisterRoute: AdminAdminRegisterRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalTenantCartIndexRoute: typeof PortalTenantCartIndexRoute
  PortalTenantConfirmedRentalSuccessIndexRoute: typeof PortalTenantConfirmedRentalSuccessIndexRoute
  PortalTenantOnboardIndexRoute: typeof PortalTenantOnboardIndexRoute
  PortalTenantOrderConfirmationIndexRoute: typeof PortalTenantOrderConfirmationIndexRoute
  PortalTenantOrderCreatedContactTeamIndexRoute: typeof PortalTenantOrderCreatedContactTeamIndexRoute
  PortalTenantOrderCreatedWhatsappIndexRoute: typeof PortalTenantOrderCreatedWhatsappIndexRoute
  PortalTenantRentalIndexRoute: typeof PortalTenantRentalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalTenantCartIndexRoute: PortalTenantCartIndexRoute,
  PortalTenantConfirmedRentalSuccessIndexRoute:
    PortalTenantConfirmedRentalSuccessIndexRoute,
  PortalTenantOnboardIndexRoute: PortalTenantOnboardIndexRoute,
  PortalTenantOrderConfirmationIndexRoute:
    PortalTenantOrderConfirmationIndexRoute,
  PortalTenantOrderCreatedContactTeamIndexRoute:
    PortalTenantOrderCreatedContactTeamIndexRoute,
  PortalTenantOrderCreatedWhatsappIndexRoute:
    PortalTenantOrderCreatedWhatsappIndexRoute,
  PortalTenantRentalIndexRoute: PortalTenantRentalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface ApiOrdersOrderIdContractSignedRouteChildren {
  ApiOrdersOrderIdContractSignedDownloadRoute: typeof ApiOrdersOrderIdContractSignedDownloadRoute
}

const ApiOrdersOrderIdContractSignedRouteChildren: ApiOrdersOrderIdContractSignedRouteChildren =
  {
    ApiOrdersOrderIdContractSignedDownloadRoute:
      ApiOrdersOrderIdContractSignedDownloadRoute,
  }

const ApiOrdersOrderIdContractSignedRouteWithChildren =
  ApiOrdersOrderIdContractSignedRoute._addFileChildren(
    ApiOrdersOrderIdContractSignedRouteChildren,
  )

interface ApiOrdersOrderIdContractRouteChildren {
  ApiOrdersOrderIdContractDownloadRoute: typeof ApiOrdersOrderIdContractDownloadRoute
  ApiOrdersOrderIdContractSignedRoute: typeof ApiOrdersOrderIdContractSignedRouteWithChildren
}

const ApiOrdersOrderIdContractRouteChildren: ApiOrdersOrderIdContractRouteChildren =
  {
    ApiOrdersOrderIdContractDownloadRoute:
      ApiOrdersOrderIdContractDownloadRoute,
    ApiOrdersOrderIdContractSignedRoute:
      ApiOrdersOrderIdContractSignedRouteWithChildren,
  }

const ApiOrdersOrderIdContractRouteWithChildren =
  ApiOrdersOrderIdContractRoute._addFileChildren(
    ApiOrdersOrderIdContractRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  SigningRoute: SigningRoute,
  ApiBrandingUploadRoute: ApiBrandingUploadRoute,
  ApiCustomerUploadRoute: ApiCustomerUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  BackendSplatRoute: BackendSplatRoute,
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute:
    ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute,
  ApiDocumentSigningPublicSignedPdfRoute:
    ApiDocumentSigningPublicSignedPdfRoute,
  ApiDocumentSigningPublicUnsignedPdfRoute:
    ApiDocumentSigningPublicUnsignedPdfRoute,
  ApiOrdersOrderIdContractRoute: ApiOrdersOrderIdContractRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
