/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendSplatRouteImport } from './routes/backend/$'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiBrandingUploadRouteImport } from './routes/api/branding-upload'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AdminDashboardSettingsRouteRouteImport } from './routes/_admin/dashboard/settings/route'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as AdminDashboardPromotionsIndexRouteImport } from './routes/_admin/dashboard/promotions/index'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/_admin/dashboard/orders/index'
import { Route as AdminDashboardInventoryIndexRouteImport } from './routes/_admin/dashboard/inventory/index'
import { Route as AdminDashboardCustomersIndexRouteImport } from './routes/_admin/dashboard/customers/index'
import { Route as AdminDashboardCalendarIndexRouteImport } from './routes/_admin/dashboard/calendar/index'
import { Route as ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport } from './routes/api/customer-profiles/$customerProfileId/identity-document'
import { Route as AdminDashboardSettingsStorefrontRouteImport } from './routes/_admin/dashboard/settings/storefront'
import { Route as AdminDashboardSettingsRentalPoliciesRouteImport } from './routes/_admin/dashboard/settings/rental-policies'
import { Route as AdminDashboardSettingsCustomerCommunicationRouteImport } from './routes/_admin/dashboard/settings/customer-communication'
import { Route as AdminDashboardSettingsContractsRouteImport } from './routes/_admin/dashboard/settings/contracts'
import { Route as AdminDashboardSettingsBusinessRouteImport } from './routes/_admin/dashboard/settings/business'
import { Route as AdminDashboardSettingsBranchesRouteImport } from './routes/_admin/dashboard/settings/branches'
import { Route as AdminDashboardPromotionsNewRouteImport } from './routes/_admin/dashboard/promotions/new'
import { Route as AdminDashboardOwnersOwnerIdRouteImport } from './routes/_admin/dashboard/owners/$ownerId'
import { Route as AdminDashboardOrdersNewRouteImport } from './routes/_admin/dashboard/orders/new'
import { Route as AdminDashboardBranchesNewRouteImport } from './routes/_admin/dashboard/branches/new'
import { Route as AdminDashboardOrdersOrderIdIndexRouteImport } from './routes/_admin/dashboard/orders/$orderId/index'
import { Route as AdminDashboardInventoryEquipmentTypesIndexRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/index'
import { Route as AdminDashboardCustomersPendingProfilesIndexRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/index'
import { Route as AdminDashboardCatalogPackagesIndexRouteImport } from './routes/_admin/dashboard/catalog/packages/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogRentableItemIdIndexRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/index'
import { Route as AdminDashboardPromotionsPromotionIdEditRouteImport } from './routes/_admin/dashboard/promotions/$promotionId/edit'
import { Route as AdminDashboardInventoryEquipmentTypesNewRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/new'
import { Route as AdminDashboardCustomersPendingProfilesCustomerIdRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/$customerId'
import { Route as AdminDashboardCatalogPackagesNewRouteImport } from './routes/_admin/dashboard/catalog/packages/new'
import { Route as AdminDashboardCatalogRentableItemIdEditRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/edit'
import { Route as AdminDashboardBranchesBranchIdEditRouteImport } from './routes/_admin/dashboard/branches/$branchId/edit'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/route'
import { Route as AdminDashboardCatalogPackagesRentableItemIdRouteRouteImport } from './routes/_admin/dashboard/catalog/packages/$rentableItemId/route'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/index'
import { Route as AdminDashboardCatalogPackagesRentableItemIdIndexRouteImport } from './routes/_admin/dashboard/catalog/packages/$rentableItemId/index'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/units'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
import { Route as AdminDashboardCatalogPackagesRentableItemIdRentalRouteImport } from './routes/_admin/dashboard/catalog/packages/$rentableItemId/rental'
import { Route as AdminDashboardCatalogPackagesRentableItemIdEquipmentRouteImport } from './routes/_admin/dashboard/catalog/packages/$rentableItemId/equipment'
import { Route as AdminDashboardCatalogPackagesRentableItemIdEditRouteImport } from './routes/_admin/dashboard/catalog/packages/$rentableItemId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendSplatRoute = BackendSplatRouteImport.update({
  id: '/backend/$',
  path: '/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingUploadRoute = ApiBrandingUploadRouteImport.update({
  id: '/api/branding-upload',
  path: '/api/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardSettingsRouteRoute =
  AdminDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardPromotionsIndexRoute =
  AdminDashboardPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryIndexRoute =
  AdminDashboardInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersIndexRoute =
  AdminDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCalendarIndexRoute =
  AdminDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute =
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport.update({
    id: '/api/customer-profiles/$customerProfileId/identity-document',
    path: '/api/customer-profiles/$customerProfileId/identity-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardSettingsStorefrontRoute =
  AdminDashboardSettingsStorefrontRouteImport.update({
    id: '/storefront',
    path: '/storefront',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardSettingsRentalPoliciesRoute =
  AdminDashboardSettingsRentalPoliciesRouteImport.update({
    id: '/rental-policies',
    path: '/rental-policies',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardSettingsCustomerCommunicationRoute =
  AdminDashboardSettingsCustomerCommunicationRouteImport.update({
    id: '/customer-communication',
    path: '/customer-communication',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardSettingsContractsRoute =
  AdminDashboardSettingsContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardSettingsBusinessRoute =
  AdminDashboardSettingsBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardSettingsBranchesRoute =
  AdminDashboardSettingsBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AdminDashboardSettingsRouteRoute,
  } as any)
const AdminDashboardPromotionsNewRoute =
  AdminDashboardPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersOwnerIdRoute =
  AdminDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersNewRoute = AdminDashboardOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardBranchesNewRoute =
  AdminDashboardBranchesNewRouteImport.update({
    id: '/branches/new',
    path: '/branches/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdIndexRoute =
  AdminDashboardOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesIndexRoute =
  AdminDashboardInventoryEquipmentTypesIndexRouteImport.update({
    id: '/inventory/equipment-types/',
    path: '/inventory/equipment-types/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesIndexRoute =
  AdminDashboardCustomersPendingProfilesIndexRouteImport.update({
    id: '/customers/pending-profiles/',
    path: '/customers/pending-profiles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesIndexRoute =
  AdminDashboardCatalogPackagesIndexRouteImport.update({
    id: '/catalog/packages/',
    path: '/catalog/packages/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdIndexRoute =
  AdminDashboardCatalogRentableItemIdIndexRouteImport.update({
    id: '/catalog/$rentableItemId/',
    path: '/catalog/$rentableItemId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsPromotionIdEditRoute =
  AdminDashboardPromotionsPromotionIdEditRouteImport.update({
    id: '/promotions/$promotionId/edit',
    path: '/promotions/$promotionId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesNewRoute =
  AdminDashboardInventoryEquipmentTypesNewRouteImport.update({
    id: '/inventory/equipment-types/new',
    path: '/inventory/equipment-types/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesCustomerIdRoute =
  AdminDashboardCustomersPendingProfilesCustomerIdRouteImport.update({
    id: '/customers/pending-profiles/$customerId',
    path: '/customers/pending-profiles/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesNewRoute =
  AdminDashboardCatalogPackagesNewRouteImport.update({
    id: '/catalog/packages/new',
    path: '/catalog/packages/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdEditRoute =
  AdminDashboardCatalogRentableItemIdEditRouteImport.update({
    id: '/catalog/$rentableItemId/edit',
    path: '/catalog/$rentableItemId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardBranchesBranchIdEditRoute =
  AdminDashboardBranchesBranchIdEditRouteImport.update({
    id: '/branches/$branchId/edit',
    path: '/branches/$branchId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteImport.update({
    id: '/inventory/equipment-types/$equipmentTypeId',
    path: '/inventory/equipment-types/$equipmentTypeId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesRentableItemIdRouteRoute =
  AdminDashboardCatalogPackagesRentableItemIdRouteRouteImport.update({
    id: '/catalog/packages/$rentableItemId',
    path: '/catalog/packages/$rentableItemId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesRentableItemIdIndexRoute =
  AdminDashboardCatalogPackagesRentableItemIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardCatalogPackagesRentableItemIdRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () =>
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRouteImport.update(
    {
      id: '/rentals',
      path: '/rentals',
      getParentRoute: () =>
        AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute,
    } as any,
  )
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRouteImport.update(
    {
      id: '/accessories',
      path: '/accessories',
      getParentRoute: () =>
        AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute,
    } as any,
  )
const AdminDashboardCatalogPackagesRentableItemIdRentalRoute =
  AdminDashboardCatalogPackagesRentableItemIdRentalRouteImport.update({
    id: '/rental',
    path: '/rental',
    getParentRoute: () => AdminDashboardCatalogPackagesRentableItemIdRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute =
  AdminDashboardCatalogPackagesRentableItemIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AdminDashboardCatalogPackagesRentableItemIdRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesRentableItemIdEditRoute =
  AdminDashboardCatalogPackagesRentableItemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminDashboardCatalogPackagesRentableItemIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/dashboard/settings': typeof AdminDashboardSettingsRouteRouteWithChildren
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/dashboard/settings/branches': typeof AdminDashboardSettingsBranchesRoute
  '/dashboard/settings/business': typeof AdminDashboardSettingsBusinessRoute
  '/dashboard/settings/contracts': typeof AdminDashboardSettingsContractsRoute
  '/dashboard/settings/customer-communication': typeof AdminDashboardSettingsCustomerCommunicationRoute
  '/dashboard/settings/rental-policies': typeof AdminDashboardSettingsRentalPoliciesRoute
  '/dashboard/settings/storefront': typeof AdminDashboardSettingsStorefrontRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/inventory/': typeof AdminDashboardInventoryIndexRoute
  '/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/catalog/packages/$rentableItemId': typeof AdminDashboardCatalogPackagesRentableItemIdRouteRouteWithChildren
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteWithChildren
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/new': typeof AdminDashboardInventoryEquipmentTypesNewRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/packages/': typeof AdminDashboardCatalogPackagesIndexRoute
  '/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/dashboard/catalog/packages/$rentableItemId/edit': typeof AdminDashboardCatalogPackagesRentableItemIdEditRoute
  '/dashboard/catalog/packages/$rentableItemId/equipment': typeof AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute
  '/dashboard/catalog/packages/$rentableItemId/rental': typeof AdminDashboardCatalogPackagesRentableItemIdRentalRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/accessories': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/rentals': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/units': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute
  '/dashboard/catalog/packages/$rentableItemId/': typeof AdminDashboardCatalogPackagesRentableItemIdIndexRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/dashboard/settings/branches': typeof AdminDashboardSettingsBranchesRoute
  '/dashboard/settings/business': typeof AdminDashboardSettingsBusinessRoute
  '/dashboard/settings/contracts': typeof AdminDashboardSettingsContractsRoute
  '/dashboard/settings/customer-communication': typeof AdminDashboardSettingsCustomerCommunicationRoute
  '/dashboard/settings/rental-policies': typeof AdminDashboardSettingsRentalPoliciesRoute
  '/dashboard/settings/storefront': typeof AdminDashboardSettingsStorefrontRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/dashboard/calendar': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/customers': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/inventory': typeof AdminDashboardInventoryIndexRoute
  '/dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/new': typeof AdminDashboardInventoryEquipmentTypesNewRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/dashboard/catalog/$rentableItemId': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/catalog/packages': typeof AdminDashboardCatalogPackagesIndexRoute
  '/dashboard/customers/pending-profiles': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/dashboard/catalog/packages/$rentableItemId/edit': typeof AdminDashboardCatalogPackagesRentableItemIdEditRoute
  '/dashboard/catalog/packages/$rentableItemId/equipment': typeof AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute
  '/dashboard/catalog/packages/$rentableItemId/rental': typeof AdminDashboardCatalogPackagesRentableItemIdRentalRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/accessories': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/rentals': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId/units': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute
  '/dashboard/catalog/packages/$rentableItemId': typeof AdminDashboardCatalogPackagesRentableItemIdIndexRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/_admin/dashboard/settings': typeof AdminDashboardSettingsRouteRouteWithChildren
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/_admin/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/_admin/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/_admin/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/_admin/dashboard/settings/branches': typeof AdminDashboardSettingsBranchesRoute
  '/_admin/dashboard/settings/business': typeof AdminDashboardSettingsBusinessRoute
  '/_admin/dashboard/settings/contracts': typeof AdminDashboardSettingsContractsRoute
  '/_admin/dashboard/settings/customer-communication': typeof AdminDashboardSettingsCustomerCommunicationRoute
  '/_admin/dashboard/settings/rental-policies': typeof AdminDashboardSettingsRentalPoliciesRoute
  '/_admin/dashboard/settings/storefront': typeof AdminDashboardSettingsStorefrontRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/_admin/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/_admin/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/_admin/dashboard/inventory/': typeof AdminDashboardInventoryIndexRoute
  '/_admin/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_admin/dashboard/catalog/packages/$rentableItemId': typeof AdminDashboardCatalogPackagesRentableItemIdRouteRouteWithChildren
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteWithChildren
  '/_admin/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/_admin/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/_admin/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/_admin/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/_admin/dashboard/inventory/equipment-types/new': typeof AdminDashboardInventoryEquipmentTypesNewRoute
  '/_admin/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/_admin/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/catalog/packages/': typeof AdminDashboardCatalogPackagesIndexRoute
  '/_admin/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/_admin/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/_admin/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
  '/_admin/dashboard/catalog/packages/$rentableItemId/edit': typeof AdminDashboardCatalogPackagesRentableItemIdEditRoute
  '/_admin/dashboard/catalog/packages/$rentableItemId/equipment': typeof AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute
  '/_admin/dashboard/catalog/packages/$rentableItemId/rental': typeof AdminDashboardCatalogPackagesRentableItemIdRentalRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/accessories': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/rentals': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/units': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute
  '/_admin/dashboard/catalog/packages/$rentableItemId/': typeof AdminDashboardCatalogPackagesRentableItemIdIndexRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/branches/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/dashboard/settings/branches'
    | '/dashboard/settings/business'
    | '/dashboard/settings/contracts'
    | '/dashboard/settings/customer-communication'
    | '/dashboard/settings/rental-policies'
    | '/dashboard/settings/storefront'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/dashboard/calendar/'
    | '/dashboard/customers/'
    | '/dashboard/inventory/'
    | '/dashboard/orders/'
    | '/dashboard/owners/'
    | '/dashboard/promotions/'
    | '/dashboard/settings/'
    | '/dashboard/catalog/packages/$rentableItemId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/$rentableItemId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/new'
    | '/dashboard/promotions/$promotionId/edit'
    | '/dashboard/catalog/$rentableItemId/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/catalog/packages/'
    | '/dashboard/customers/pending-profiles/'
    | '/dashboard/inventory/equipment-types/'
    | '/dashboard/orders/$orderId/'
    | '/dashboard/catalog/packages/$rentableItemId/edit'
    | '/dashboard/catalog/packages/$rentableItemId/equipment'
    | '/dashboard/catalog/packages/$rentableItemId/rental'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/units'
    | '/dashboard/catalog/packages/$rentableItemId/'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/dashboard'
    | '/dashboard/branches/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/dashboard/settings/branches'
    | '/dashboard/settings/business'
    | '/dashboard/settings/contracts'
    | '/dashboard/settings/customer-communication'
    | '/dashboard/settings/rental-policies'
    | '/dashboard/settings/storefront'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/dashboard/calendar'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/owners'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/$rentableItemId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/new'
    | '/dashboard/promotions/$promotionId/edit'
    | '/dashboard/catalog/$rentableItemId'
    | '/dashboard/catalog/categories'
    | '/dashboard/catalog/packages'
    | '/dashboard/customers/pending-profiles'
    | '/dashboard/inventory/equipment-types'
    | '/dashboard/orders/$orderId'
    | '/dashboard/catalog/packages/$rentableItemId/edit'
    | '/dashboard/catalog/packages/$rentableItemId/equipment'
    | '/dashboard/catalog/packages/$rentableItemId/rental'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId/units'
    | '/dashboard/catalog/packages/$rentableItemId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_admin/dashboard'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/_admin/dashboard/settings'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/branches/new'
    | '/_admin/dashboard/orders/new'
    | '/_admin/dashboard/owners/$ownerId'
    | '/_admin/dashboard/promotions/new'
    | '/_admin/dashboard/settings/branches'
    | '/_admin/dashboard/settings/business'
    | '/_admin/dashboard/settings/contracts'
    | '/_admin/dashboard/settings/customer-communication'
    | '/_admin/dashboard/settings/rental-policies'
    | '/_admin/dashboard/settings/storefront'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/_admin/dashboard/calendar/'
    | '/_admin/dashboard/customers/'
    | '/_admin/dashboard/inventory/'
    | '/_admin/dashboard/orders/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/promotions/'
    | '/_admin/dashboard/settings/'
    | '/_admin/dashboard/catalog/packages/$rentableItemId'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/_admin/dashboard/branches/$branchId/edit'
    | '/_admin/dashboard/catalog/$rentableItemId/edit'
    | '/_admin/dashboard/catalog/packages/new'
    | '/_admin/dashboard/customers/pending-profiles/$customerId'
    | '/_admin/dashboard/inventory/equipment-types/new'
    | '/_admin/dashboard/promotions/$promotionId/edit'
    | '/_admin/dashboard/catalog/$rentableItemId/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/catalog/packages/'
    | '/_admin/dashboard/customers/pending-profiles/'
    | '/_admin/dashboard/inventory/equipment-types/'
    | '/_admin/dashboard/orders/$orderId/'
    | '/_admin/dashboard/catalog/packages/$rentableItemId/edit'
    | '/_admin/dashboard/catalog/packages/$rentableItemId/equipment'
    | '/_admin/dashboard/catalog/packages/$rentableItemId/rental'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/units'
    | '/_admin/dashboard/catalog/packages/$rentableItemId/'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiBrandingUploadRoute: typeof ApiBrandingUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BackendSplatRoute: typeof BackendSplatRoute
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/$': {
      id: '/backend/$'
      path: '/backend/$'
      fullPath: '/backend/$'
      preLoaderRoute: typeof BackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding-upload': {
      id: '/api/branding-upload'
      path: '/api/branding-upload'
      fullPath: '/api/branding-upload'
      preLoaderRoute: typeof ApiBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/settings': {
      id: '/_admin/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/promotions/': {
      id: '/_admin/dashboard/promotions/'
      path: '/promotions'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof AdminDashboardPromotionsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/': {
      id: '/_admin/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/': {
      id: '/_admin/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof AdminDashboardInventoryIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/': {
      id: '/_admin/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AdminDashboardCustomersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/calendar/': {
      id: '/_admin/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof AdminDashboardCalendarIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/customer-profiles/$customerProfileId/identity-document': {
      id: '/api/customer-profiles/$customerProfileId/identity-document'
      path: '/api/customer-profiles/$customerProfileId/identity-document'
      fullPath: '/api/customer-profiles/$customerProfileId/identity-document'
      preLoaderRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/settings/storefront': {
      id: '/_admin/dashboard/settings/storefront'
      path: '/storefront'
      fullPath: '/dashboard/settings/storefront'
      preLoaderRoute: typeof AdminDashboardSettingsStorefrontRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/settings/rental-policies': {
      id: '/_admin/dashboard/settings/rental-policies'
      path: '/rental-policies'
      fullPath: '/dashboard/settings/rental-policies'
      preLoaderRoute: typeof AdminDashboardSettingsRentalPoliciesRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/settings/customer-communication': {
      id: '/_admin/dashboard/settings/customer-communication'
      path: '/customer-communication'
      fullPath: '/dashboard/settings/customer-communication'
      preLoaderRoute: typeof AdminDashboardSettingsCustomerCommunicationRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/settings/contracts': {
      id: '/_admin/dashboard/settings/contracts'
      path: '/contracts'
      fullPath: '/dashboard/settings/contracts'
      preLoaderRoute: typeof AdminDashboardSettingsContractsRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/settings/business': {
      id: '/_admin/dashboard/settings/business'
      path: '/business'
      fullPath: '/dashboard/settings/business'
      preLoaderRoute: typeof AdminDashboardSettingsBusinessRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/settings/branches': {
      id: '/_admin/dashboard/settings/branches'
      path: '/branches'
      fullPath: '/dashboard/settings/branches'
      preLoaderRoute: typeof AdminDashboardSettingsBranchesRouteImport
      parentRoute: typeof AdminDashboardSettingsRouteRoute
    }
    '/_admin/dashboard/promotions/new': {
      id: '/_admin/dashboard/promotions/new'
      path: '/promotions/new'
      fullPath: '/dashboard/promotions/new'
      preLoaderRoute: typeof AdminDashboardPromotionsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/$ownerId': {
      id: '/_admin/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/dashboard/owners/$ownerId'
      preLoaderRoute: typeof AdminDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/new': {
      id: '/_admin/dashboard/orders/new'
      path: '/orders/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof AdminDashboardOrdersNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/new': {
      id: '/_admin/dashboard/branches/new'
      path: '/branches/new'
      fullPath: '/dashboard/branches/new'
      preLoaderRoute: typeof AdminDashboardBranchesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId/': {
      id: '/_admin/dashboard/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/': {
      id: '/_admin/dashboard/inventory/equipment-types/'
      path: '/inventory/equipment-types'
      fullPath: '/dashboard/inventory/equipment-types/'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/': {
      id: '/_admin/dashboard/customers/pending-profiles/'
      path: '/customers/pending-profiles'
      fullPath: '/dashboard/customers/pending-profiles/'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/': {
      id: '/_admin/dashboard/catalog/packages/'
      path: '/catalog/packages'
      fullPath: '/dashboard/catalog/packages/'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/': {
      id: '/_admin/dashboard/catalog/$rentableItemId/'
      path: '/catalog/$rentableItemId'
      fullPath: '/dashboard/catalog/$rentableItemId/'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/$promotionId/edit': {
      id: '/_admin/dashboard/promotions/$promotionId/edit'
      path: '/promotions/$promotionId/edit'
      fullPath: '/dashboard/promotions/$promotionId/edit'
      preLoaderRoute: typeof AdminDashboardPromotionsPromotionIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/new': {
      id: '/_admin/dashboard/inventory/equipment-types/new'
      path: '/inventory/equipment-types/new'
      fullPath: '/dashboard/inventory/equipment-types/new'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/$customerId': {
      id: '/_admin/dashboard/customers/pending-profiles/$customerId'
      path: '/customers/pending-profiles/$customerId'
      fullPath: '/dashboard/customers/pending-profiles/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/new': {
      id: '/_admin/dashboard/catalog/packages/new'
      path: '/catalog/packages/new'
      fullPath: '/dashboard/catalog/packages/new'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/edit': {
      id: '/_admin/dashboard/catalog/$rentableItemId/edit'
      path: '/catalog/$rentableItemId/edit'
      fullPath: '/dashboard/catalog/$rentableItemId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/$branchId/edit': {
      id: '/_admin/dashboard/branches/$branchId/edit'
      path: '/branches/$branchId/edit'
      fullPath: '/dashboard/branches/$branchId/edit'
      preLoaderRoute: typeof AdminDashboardBranchesBranchIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
      path: '/inventory/equipment-types/$equipmentTypeId'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/$rentableItemId': {
      id: '/_admin/dashboard/catalog/packages/$rentableItemId'
      path: '/catalog/packages/$rentableItemId'
      fullPath: '/dashboard/catalog/packages/$rentableItemId'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/'
      path: '/'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId/'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRouteImport
      parentRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute
    }
    '/_admin/dashboard/catalog/packages/$rentableItemId/': {
      id: '/_admin/dashboard/catalog/packages/$rentableItemId/'
      path: '/'
      fullPath: '/dashboard/catalog/packages/$rentableItemId/'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesRentableItemIdIndexRouteImport
      parentRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/units': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/units'
      path: '/units'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId/units'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRouteImport
      parentRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/rentals': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
      path: '/rentals'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId/rentals'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRouteImport
      parentRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/accessories': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
      path: '/accessories'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId/accessories'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRouteImport
      parentRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute
    }
    '/_admin/dashboard/catalog/packages/$rentableItemId/rental': {
      id: '/_admin/dashboard/catalog/packages/$rentableItemId/rental'
      path: '/rental'
      fullPath: '/dashboard/catalog/packages/$rentableItemId/rental'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRentalRouteImport
      parentRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRoute
    }
    '/_admin/dashboard/catalog/packages/$rentableItemId/equipment': {
      id: '/_admin/dashboard/catalog/packages/$rentableItemId/equipment'
      path: '/equipment'
      fullPath: '/dashboard/catalog/packages/$rentableItemId/equipment'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesRentableItemIdEquipmentRouteImport
      parentRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRoute
    }
    '/_admin/dashboard/catalog/packages/$rentableItemId/edit': {
      id: '/_admin/dashboard/catalog/packages/$rentableItemId/edit'
      path: '/edit'
      fullPath: '/dashboard/catalog/packages/$rentableItemId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesRentableItemIdEditRouteImport
      parentRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRoute
    }
  }
}

interface AdminDashboardSettingsRouteRouteChildren {
  AdminDashboardSettingsBranchesRoute: typeof AdminDashboardSettingsBranchesRoute
  AdminDashboardSettingsBusinessRoute: typeof AdminDashboardSettingsBusinessRoute
  AdminDashboardSettingsContractsRoute: typeof AdminDashboardSettingsContractsRoute
  AdminDashboardSettingsCustomerCommunicationRoute: typeof AdminDashboardSettingsCustomerCommunicationRoute
  AdminDashboardSettingsRentalPoliciesRoute: typeof AdminDashboardSettingsRentalPoliciesRoute
  AdminDashboardSettingsStorefrontRoute: typeof AdminDashboardSettingsStorefrontRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
}

const AdminDashboardSettingsRouteRouteChildren: AdminDashboardSettingsRouteRouteChildren =
  {
    AdminDashboardSettingsBranchesRoute: AdminDashboardSettingsBranchesRoute,
    AdminDashboardSettingsBusinessRoute: AdminDashboardSettingsBusinessRoute,
    AdminDashboardSettingsContractsRoute: AdminDashboardSettingsContractsRoute,
    AdminDashboardSettingsCustomerCommunicationRoute:
      AdminDashboardSettingsCustomerCommunicationRoute,
    AdminDashboardSettingsRentalPoliciesRoute:
      AdminDashboardSettingsRentalPoliciesRoute,
    AdminDashboardSettingsStorefrontRoute:
      AdminDashboardSettingsStorefrontRoute,
    AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  }

const AdminDashboardSettingsRouteRouteWithChildren =
  AdminDashboardSettingsRouteRoute._addFileChildren(
    AdminDashboardSettingsRouteRouteChildren,
  )

interface AdminDashboardCatalogPackagesRentableItemIdRouteRouteChildren {
  AdminDashboardCatalogPackagesRentableItemIdEditRoute: typeof AdminDashboardCatalogPackagesRentableItemIdEditRoute
  AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute: typeof AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute
  AdminDashboardCatalogPackagesRentableItemIdRentalRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRentalRoute
  AdminDashboardCatalogPackagesRentableItemIdIndexRoute: typeof AdminDashboardCatalogPackagesRentableItemIdIndexRoute
}

const AdminDashboardCatalogPackagesRentableItemIdRouteRouteChildren: AdminDashboardCatalogPackagesRentableItemIdRouteRouteChildren =
  {
    AdminDashboardCatalogPackagesRentableItemIdEditRoute:
      AdminDashboardCatalogPackagesRentableItemIdEditRoute,
    AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute:
      AdminDashboardCatalogPackagesRentableItemIdEquipmentRoute,
    AdminDashboardCatalogPackagesRentableItemIdRentalRoute:
      AdminDashboardCatalogPackagesRentableItemIdRentalRoute,
    AdminDashboardCatalogPackagesRentableItemIdIndexRoute:
      AdminDashboardCatalogPackagesRentableItemIdIndexRoute,
  }

const AdminDashboardCatalogPackagesRentableItemIdRouteRouteWithChildren =
  AdminDashboardCatalogPackagesRentableItemIdRouteRoute._addFileChildren(
    AdminDashboardCatalogPackagesRentableItemIdRouteRouteChildren,
  )

interface AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteChildren {
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute
}

const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteChildren: AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteChildren =
  {
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute:
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdAccessoriesRoute,
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute:
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRentalsRoute,
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute:
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdUnitsRoute,
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute:
      AdminDashboardInventoryEquipmentTypesEquipmentTypeIdIndexRoute,
  }

const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteWithChildren =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute._addFileChildren(
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteChildren,
  )

interface AdminDashboardRouteRouteChildren {
  AdminDashboardSettingsRouteRoute: typeof AdminDashboardSettingsRouteRouteWithChildren
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBranchesNewRoute: typeof AdminDashboardBranchesNewRoute
  AdminDashboardOrdersNewRoute: typeof AdminDashboardOrdersNewRoute
  AdminDashboardOwnersOwnerIdRoute: typeof AdminDashboardOwnersOwnerIdRoute
  AdminDashboardPromotionsNewRoute: typeof AdminDashboardPromotionsNewRoute
  AdminDashboardCalendarIndexRoute: typeof AdminDashboardCalendarIndexRoute
  AdminDashboardCustomersIndexRoute: typeof AdminDashboardCustomersIndexRoute
  AdminDashboardInventoryIndexRoute: typeof AdminDashboardInventoryIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardPromotionsIndexRoute: typeof AdminDashboardPromotionsIndexRoute
  AdminDashboardCatalogPackagesRentableItemIdRouteRoute: typeof AdminDashboardCatalogPackagesRentableItemIdRouteRouteWithChildren
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteWithChildren
  AdminDashboardBranchesBranchIdEditRoute: typeof AdminDashboardBranchesBranchIdEditRoute
  AdminDashboardCatalogRentableItemIdEditRoute: typeof AdminDashboardCatalogRentableItemIdEditRoute
  AdminDashboardCatalogPackagesNewRoute: typeof AdminDashboardCatalogPackagesNewRoute
  AdminDashboardCustomersPendingProfilesCustomerIdRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  AdminDashboardInventoryEquipmentTypesNewRoute: typeof AdminDashboardInventoryEquipmentTypesNewRoute
  AdminDashboardPromotionsPromotionIdEditRoute: typeof AdminDashboardPromotionsPromotionIdEditRoute
  AdminDashboardCatalogRentableItemIdIndexRoute: typeof AdminDashboardCatalogRentableItemIdIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCatalogPackagesIndexRoute: typeof AdminDashboardCatalogPackagesIndexRoute
  AdminDashboardCustomersPendingProfilesIndexRoute: typeof AdminDashboardCustomersPendingProfilesIndexRoute
  AdminDashboardInventoryEquipmentTypesIndexRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  AdminDashboardOrdersOrderIdIndexRoute: typeof AdminDashboardOrdersOrderIdIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardSettingsRouteRoute:
    AdminDashboardSettingsRouteRouteWithChildren,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBranchesNewRoute: AdminDashboardBranchesNewRoute,
  AdminDashboardOrdersNewRoute: AdminDashboardOrdersNewRoute,
  AdminDashboardOwnersOwnerIdRoute: AdminDashboardOwnersOwnerIdRoute,
  AdminDashboardPromotionsNewRoute: AdminDashboardPromotionsNewRoute,
  AdminDashboardCalendarIndexRoute: AdminDashboardCalendarIndexRoute,
  AdminDashboardCustomersIndexRoute: AdminDashboardCustomersIndexRoute,
  AdminDashboardInventoryIndexRoute: AdminDashboardInventoryIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardPromotionsIndexRoute: AdminDashboardPromotionsIndexRoute,
  AdminDashboardCatalogPackagesRentableItemIdRouteRoute:
    AdminDashboardCatalogPackagesRentableItemIdRouteRouteWithChildren,
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRoute:
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteRouteWithChildren,
  AdminDashboardBranchesBranchIdEditRoute:
    AdminDashboardBranchesBranchIdEditRoute,
  AdminDashboardCatalogRentableItemIdEditRoute:
    AdminDashboardCatalogRentableItemIdEditRoute,
  AdminDashboardCatalogPackagesNewRoute: AdminDashboardCatalogPackagesNewRoute,
  AdminDashboardCustomersPendingProfilesCustomerIdRoute:
    AdminDashboardCustomersPendingProfilesCustomerIdRoute,
  AdminDashboardInventoryEquipmentTypesNewRoute:
    AdminDashboardInventoryEquipmentTypesNewRoute,
  AdminDashboardPromotionsPromotionIdEditRoute:
    AdminDashboardPromotionsPromotionIdEditRoute,
  AdminDashboardCatalogRentableItemIdIndexRoute:
    AdminDashboardCatalogRentableItemIdIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCatalogPackagesIndexRoute:
    AdminDashboardCatalogPackagesIndexRoute,
  AdminDashboardCustomersPendingProfilesIndexRoute:
    AdminDashboardCustomersPendingProfilesIndexRoute,
  AdminDashboardInventoryEquipmentTypesIndexRoute:
    AdminDashboardInventoryEquipmentTypesIndexRoute,
  AdminDashboardOrdersOrderIdIndexRoute: AdminDashboardOrdersOrderIdIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiBrandingUploadRoute: ApiBrandingUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  BackendSplatRoute: BackendSplatRoute,
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute:
    ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
