/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendSplatRouteImport } from './routes/backend/$'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiBrandingUploadRouteImport } from './routes/api/branding-upload'
import { Route as AdminDashboardRouteRouteImport } from './routes/_admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AdminAdminRegisterRouteImport } from './routes/_admin/admin/register'
import { Route as AdminDashboardSettingsIndexRouteImport } from './routes/_admin/dashboard/settings/index'
import { Route as AdminDashboardPromotionsIndexRouteImport } from './routes/_admin/dashboard/promotions/index'
import { Route as AdminDashboardOwnersIndexRouteImport } from './routes/_admin/dashboard/owners/index'
import { Route as AdminDashboardOrdersIndexRouteImport } from './routes/_admin/dashboard/orders/index'
import { Route as AdminDashboardCustomersIndexRouteImport } from './routes/_admin/dashboard/customers/index'
import { Route as AdminDashboardCatalogIndexRouteImport } from './routes/_admin/dashboard/catalog/index'
import { Route as AdminDashboardCalendarIndexRouteImport } from './routes/_admin/dashboard/calendar/index'
import { Route as ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport } from './routes/api/customer-profiles/$customerProfileId/identity-document'
import { Route as AdminDashboardPromotionsNewRouteImport } from './routes/_admin/dashboard/promotions/new'
import { Route as AdminDashboardOwnersOwnerIdRouteImport } from './routes/_admin/dashboard/owners/$ownerId'
import { Route as AdminDashboardOrdersNewRouteImport } from './routes/_admin/dashboard/orders/new'
import { Route as AdminDashboardCatalogNewRouteImport } from './routes/_admin/dashboard/catalog/new'
import { Route as AdminDashboardBranchesNewRouteImport } from './routes/_admin/dashboard/branches/new'
import { Route as AdminDashboardOrdersOrderIdIndexRouteImport } from './routes/_admin/dashboard/orders/$orderId/index'
import { Route as AdminDashboardInventoryEquipmentTypesIndexRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/index'
import { Route as AdminDashboardCustomersPendingProfilesIndexRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/index'
import { Route as AdminDashboardCatalogCategoriesIndexRouteImport } from './routes/_admin/dashboard/catalog/categories/index'
import { Route as AdminDashboardCatalogRentableItemIdIndexRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/index'
import { Route as AdminDashboardPromotionsPromotionIdEditRouteImport } from './routes/_admin/dashboard/promotions/$promotionId/edit'
import { Route as AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport } from './routes/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
import { Route as AdminDashboardCustomersPendingProfilesCustomerIdRouteImport } from './routes/_admin/dashboard/customers/pending-profiles/$customerId'
import { Route as AdminDashboardCatalogPackagesNewRouteImport } from './routes/_admin/dashboard/catalog/packages/new'
import { Route as AdminDashboardCatalogRentableItemIdEditRouteImport } from './routes/_admin/dashboard/catalog/$rentableItemId/edit'
import { Route as AdminDashboardBranchesBranchIdEditRouteImport } from './routes/_admin/dashboard/branches/$branchId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendSplatRoute = BackendSplatRouteImport.update({
  id: '/backend/$',
  path: '/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingUploadRoute = ApiBrandingUploadRouteImport.update({
  id: '/api/branding-upload',
  path: '/api/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminAdminRegisterRoute = AdminAdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardSettingsIndexRoute =
  AdminDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsIndexRoute =
  AdminDashboardPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersIndexRoute =
  AdminDashboardOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersIndexRoute =
  AdminDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersIndexRoute =
  AdminDashboardCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogIndexRoute =
  AdminDashboardCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCalendarIndexRoute =
  AdminDashboardCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute =
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport.update({
    id: '/api/customer-profiles/$customerProfileId/identity-document',
    path: '/api/customer-profiles/$customerProfileId/identity-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardPromotionsNewRoute =
  AdminDashboardPromotionsNewRouteImport.update({
    id: '/promotions/new',
    path: '/promotions/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOwnersOwnerIdRoute =
  AdminDashboardOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersNewRoute = AdminDashboardOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardCatalogNewRoute =
  AdminDashboardCatalogNewRouteImport.update({
    id: '/catalog/new',
    path: '/catalog/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardBranchesNewRoute =
  AdminDashboardBranchesNewRouteImport.update({
    id: '/branches/new',
    path: '/branches/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrdersOrderIdIndexRoute =
  AdminDashboardOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesIndexRoute =
  AdminDashboardInventoryEquipmentTypesIndexRouteImport.update({
    id: '/inventory/equipment-types/',
    path: '/inventory/equipment-types/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesIndexRoute =
  AdminDashboardCustomersPendingProfilesIndexRouteImport.update({
    id: '/customers/pending-profiles/',
    path: '/customers/pending-profiles/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogCategoriesIndexRoute =
  AdminDashboardCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdIndexRoute =
  AdminDashboardCatalogRentableItemIdIndexRouteImport.update({
    id: '/catalog/$rentableItemId/',
    path: '/catalog/$rentableItemId/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPromotionsPromotionIdEditRoute =
  AdminDashboardPromotionsPromotionIdEditRouteImport.update({
    id: '/promotions/$promotionId/edit',
    path: '/promotions/$promotionId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute =
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport.update({
    id: '/inventory/equipment-types/$equipmentTypeId',
    path: '/inventory/equipment-types/$equipmentTypeId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCustomersPendingProfilesCustomerIdRoute =
  AdminDashboardCustomersPendingProfilesCustomerIdRouteImport.update({
    id: '/customers/pending-profiles/$customerId',
    path: '/customers/pending-profiles/$customerId',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogPackagesNewRoute =
  AdminDashboardCatalogPackagesNewRouteImport.update({
    id: '/catalog/packages/new',
    path: '/catalog/packages/new',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardCatalogRentableItemIdEditRoute =
  AdminDashboardCatalogRentableItemIdEditRouteImport.update({
    id: '/catalog/$rentableItemId/edit',
    path: '/catalog/$rentableItemId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardBranchesBranchIdEditRoute =
  AdminDashboardBranchesBranchIdEditRouteImport.update({
    id: '/branches/$branchId/edit',
    path: '/branches/$branchId/edit',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/admin/register': typeof AdminAdminRegisterRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/dashboard/calendar': typeof AdminDashboardCalendarIndexRoute
  '/dashboard/catalog': typeof AdminDashboardCatalogIndexRoute
  '/dashboard/customers': typeof AdminDashboardCustomersIndexRoute
  '/dashboard/orders': typeof AdminDashboardOrdersIndexRoute
  '/dashboard/owners': typeof AdminDashboardOwnersIndexRoute
  '/dashboard/promotions': typeof AdminDashboardPromotionsIndexRoute
  '/dashboard/settings': typeof AdminDashboardSettingsIndexRoute
  '/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/dashboard/catalog/$rentableItemId': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/dashboard/catalog/categories': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/dashboard/customers/pending-profiles': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/dashboard/inventory/equipment-types': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/dashboard/orders/$orderId': typeof AdminDashboardOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/api/branding-upload': typeof ApiBrandingUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/backend/$': typeof BackendSplatRoute
  '/_admin/admin/register': typeof AdminAdminRegisterRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/branches/new': typeof AdminDashboardBranchesNewRoute
  '/_admin/dashboard/catalog/new': typeof AdminDashboardCatalogNewRoute
  '/_admin/dashboard/orders/new': typeof AdminDashboardOrdersNewRoute
  '/_admin/dashboard/owners/$ownerId': typeof AdminDashboardOwnersOwnerIdRoute
  '/_admin/dashboard/promotions/new': typeof AdminDashboardPromotionsNewRoute
  '/api/customer-profiles/$customerProfileId/identity-document': typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
  '/_admin/dashboard/calendar/': typeof AdminDashboardCalendarIndexRoute
  '/_admin/dashboard/catalog/': typeof AdminDashboardCatalogIndexRoute
  '/_admin/dashboard/customers/': typeof AdminDashboardCustomersIndexRoute
  '/_admin/dashboard/orders/': typeof AdminDashboardOrdersIndexRoute
  '/_admin/dashboard/owners/': typeof AdminDashboardOwnersIndexRoute
  '/_admin/dashboard/promotions/': typeof AdminDashboardPromotionsIndexRoute
  '/_admin/dashboard/settings/': typeof AdminDashboardSettingsIndexRoute
  '/_admin/dashboard/branches/$branchId/edit': typeof AdminDashboardBranchesBranchIdEditRoute
  '/_admin/dashboard/catalog/$rentableItemId/edit': typeof AdminDashboardCatalogRentableItemIdEditRoute
  '/_admin/dashboard/catalog/packages/new': typeof AdminDashboardCatalogPackagesNewRoute
  '/_admin/dashboard/customers/pending-profiles/$customerId': typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  '/_admin/dashboard/promotions/$promotionId/edit': typeof AdminDashboardPromotionsPromotionIdEditRoute
  '/_admin/dashboard/catalog/$rentableItemId/': typeof AdminDashboardCatalogRentableItemIdIndexRoute
  '/_admin/dashboard/catalog/categories/': typeof AdminDashboardCatalogCategoriesIndexRoute
  '/_admin/dashboard/customers/pending-profiles/': typeof AdminDashboardCustomersPendingProfilesIndexRoute
  '/_admin/dashboard/inventory/equipment-types/': typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  '/_admin/dashboard/orders/$orderId/': typeof AdminDashboardOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/admin/register'
    | '/dashboard/'
    | '/dashboard/branches/new'
    | '/dashboard/catalog/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/dashboard/calendar/'
    | '/dashboard/catalog/'
    | '/dashboard/customers/'
    | '/dashboard/orders/'
    | '/dashboard/owners/'
    | '/dashboard/promotions/'
    | '/dashboard/settings/'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/$rentableItemId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/dashboard/catalog/$rentableItemId/'
    | '/dashboard/catalog/categories/'
    | '/dashboard/customers/pending-profiles/'
    | '/dashboard/inventory/equipment-types/'
    | '/dashboard/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/admin/register'
    | '/dashboard'
    | '/dashboard/branches/new'
    | '/dashboard/catalog/new'
    | '/dashboard/orders/new'
    | '/dashboard/owners/$ownerId'
    | '/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/dashboard/calendar'
    | '/dashboard/catalog'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/owners'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/branches/$branchId/edit'
    | '/dashboard/catalog/$rentableItemId/edit'
    | '/dashboard/catalog/packages/new'
    | '/dashboard/customers/pending-profiles/$customerId'
    | '/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/dashboard/promotions/$promotionId/edit'
    | '/dashboard/catalog/$rentableItemId'
    | '/dashboard/catalog/categories'
    | '/dashboard/customers/pending-profiles'
    | '/dashboard/inventory/equipment-types'
    | '/dashboard/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/dashboard'
    | '/api/branding-upload'
    | '/api/upload'
    | '/backend/$'
    | '/_admin/admin/register'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/branches/new'
    | '/_admin/dashboard/catalog/new'
    | '/_admin/dashboard/orders/new'
    | '/_admin/dashboard/owners/$ownerId'
    | '/_admin/dashboard/promotions/new'
    | '/api/customer-profiles/$customerProfileId/identity-document'
    | '/_admin/dashboard/calendar/'
    | '/_admin/dashboard/catalog/'
    | '/_admin/dashboard/customers/'
    | '/_admin/dashboard/orders/'
    | '/_admin/dashboard/owners/'
    | '/_admin/dashboard/promotions/'
    | '/_admin/dashboard/settings/'
    | '/_admin/dashboard/branches/$branchId/edit'
    | '/_admin/dashboard/catalog/$rentableItemId/edit'
    | '/_admin/dashboard/catalog/packages/new'
    | '/_admin/dashboard/customers/pending-profiles/$customerId'
    | '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
    | '/_admin/dashboard/promotions/$promotionId/edit'
    | '/_admin/dashboard/catalog/$rentableItemId/'
    | '/_admin/dashboard/catalog/categories/'
    | '/_admin/dashboard/customers/pending-profiles/'
    | '/_admin/dashboard/inventory/equipment-types/'
    | '/_admin/dashboard/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiBrandingUploadRoute: typeof ApiBrandingUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BackendSplatRoute: typeof BackendSplatRoute
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/$': {
      id: '/backend/$'
      path: '/backend/$'
      fullPath: '/backend/$'
      preLoaderRoute: typeof BackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding-upload': {
      id: '/api/branding-upload'
      path: '/api/branding-upload'
      fullPath: '/api/branding-upload'
      preLoaderRoute: typeof ApiBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/admin/register': {
      id: '/_admin/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminAdminRegisterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard/settings/': {
      id: '/_admin/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AdminDashboardSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/': {
      id: '/_admin/dashboard/promotions/'
      path: '/promotions'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof AdminDashboardPromotionsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/': {
      id: '/_admin/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners/'
      preLoaderRoute: typeof AdminDashboardOwnersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/': {
      id: '/_admin/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AdminDashboardOrdersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/': {
      id: '/_admin/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AdminDashboardCustomersIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/': {
      id: '/_admin/dashboard/catalog/'
      path: '/catalog'
      fullPath: '/dashboard/catalog/'
      preLoaderRoute: typeof AdminDashboardCatalogIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/calendar/': {
      id: '/_admin/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof AdminDashboardCalendarIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/api/customer-profiles/$customerProfileId/identity-document': {
      id: '/api/customer-profiles/$customerProfileId/identity-document'
      path: '/api/customer-profiles/$customerProfileId/identity-document'
      fullPath: '/api/customer-profiles/$customerProfileId/identity-document'
      preLoaderRoute: typeof ApiCustomerProfilesCustomerProfileIdIdentityDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/promotions/new': {
      id: '/_admin/dashboard/promotions/new'
      path: '/promotions/new'
      fullPath: '/dashboard/promotions/new'
      preLoaderRoute: typeof AdminDashboardPromotionsNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/owners/$ownerId': {
      id: '/_admin/dashboard/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/dashboard/owners/$ownerId'
      preLoaderRoute: typeof AdminDashboardOwnersOwnerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/new': {
      id: '/_admin/dashboard/orders/new'
      path: '/orders/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof AdminDashboardOrdersNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/new': {
      id: '/_admin/dashboard/catalog/new'
      path: '/catalog/new'
      fullPath: '/dashboard/catalog/new'
      preLoaderRoute: typeof AdminDashboardCatalogNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/new': {
      id: '/_admin/dashboard/branches/new'
      path: '/branches/new'
      fullPath: '/dashboard/branches/new'
      preLoaderRoute: typeof AdminDashboardBranchesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/orders/$orderId/': {
      id: '/_admin/dashboard/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof AdminDashboardOrdersOrderIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/': {
      id: '/_admin/dashboard/inventory/equipment-types/'
      path: '/inventory/equipment-types'
      fullPath: '/dashboard/inventory/equipment-types/'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/': {
      id: '/_admin/dashboard/customers/pending-profiles/'
      path: '/customers/pending-profiles'
      fullPath: '/dashboard/customers/pending-profiles/'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/categories/': {
      id: '/_admin/dashboard/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/dashboard/catalog/categories/'
      preLoaderRoute: typeof AdminDashboardCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/': {
      id: '/_admin/dashboard/catalog/$rentableItemId/'
      path: '/catalog/$rentableItemId'
      fullPath: '/dashboard/catalog/$rentableItemId/'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/promotions/$promotionId/edit': {
      id: '/_admin/dashboard/promotions/$promotionId/edit'
      path: '/promotions/$promotionId/edit'
      fullPath: '/dashboard/promotions/$promotionId/edit'
      preLoaderRoute: typeof AdminDashboardPromotionsPromotionIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId': {
      id: '/_admin/dashboard/inventory/equipment-types/$equipmentTypeId'
      path: '/inventory/equipment-types/$equipmentTypeId'
      fullPath: '/dashboard/inventory/equipment-types/$equipmentTypeId'
      preLoaderRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/customers/pending-profiles/$customerId': {
      id: '/_admin/dashboard/customers/pending-profiles/$customerId'
      path: '/customers/pending-profiles/$customerId'
      fullPath: '/dashboard/customers/pending-profiles/$customerId'
      preLoaderRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/packages/new': {
      id: '/_admin/dashboard/catalog/packages/new'
      path: '/catalog/packages/new'
      fullPath: '/dashboard/catalog/packages/new'
      preLoaderRoute: typeof AdminDashboardCatalogPackagesNewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/catalog/$rentableItemId/edit': {
      id: '/_admin/dashboard/catalog/$rentableItemId/edit'
      path: '/catalog/$rentableItemId/edit'
      fullPath: '/dashboard/catalog/$rentableItemId/edit'
      preLoaderRoute: typeof AdminDashboardCatalogRentableItemIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_admin/dashboard/branches/$branchId/edit': {
      id: '/_admin/dashboard/branches/$branchId/edit'
      path: '/branches/$branchId/edit'
      fullPath: '/dashboard/branches/$branchId/edit'
      preLoaderRoute: typeof AdminDashboardBranchesBranchIdEditRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBranchesNewRoute: typeof AdminDashboardBranchesNewRoute
  AdminDashboardCatalogNewRoute: typeof AdminDashboardCatalogNewRoute
  AdminDashboardOrdersNewRoute: typeof AdminDashboardOrdersNewRoute
  AdminDashboardOwnersOwnerIdRoute: typeof AdminDashboardOwnersOwnerIdRoute
  AdminDashboardPromotionsNewRoute: typeof AdminDashboardPromotionsNewRoute
  AdminDashboardCalendarIndexRoute: typeof AdminDashboardCalendarIndexRoute
  AdminDashboardCatalogIndexRoute: typeof AdminDashboardCatalogIndexRoute
  AdminDashboardCustomersIndexRoute: typeof AdminDashboardCustomersIndexRoute
  AdminDashboardOrdersIndexRoute: typeof AdminDashboardOrdersIndexRoute
  AdminDashboardOwnersIndexRoute: typeof AdminDashboardOwnersIndexRoute
  AdminDashboardPromotionsIndexRoute: typeof AdminDashboardPromotionsIndexRoute
  AdminDashboardSettingsIndexRoute: typeof AdminDashboardSettingsIndexRoute
  AdminDashboardBranchesBranchIdEditRoute: typeof AdminDashboardBranchesBranchIdEditRoute
  AdminDashboardCatalogRentableItemIdEditRoute: typeof AdminDashboardCatalogRentableItemIdEditRoute
  AdminDashboardCatalogPackagesNewRoute: typeof AdminDashboardCatalogPackagesNewRoute
  AdminDashboardCustomersPendingProfilesCustomerIdRoute: typeof AdminDashboardCustomersPendingProfilesCustomerIdRoute
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute: typeof AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute
  AdminDashboardPromotionsPromotionIdEditRoute: typeof AdminDashboardPromotionsPromotionIdEditRoute
  AdminDashboardCatalogRentableItemIdIndexRoute: typeof AdminDashboardCatalogRentableItemIdIndexRoute
  AdminDashboardCatalogCategoriesIndexRoute: typeof AdminDashboardCatalogCategoriesIndexRoute
  AdminDashboardCustomersPendingProfilesIndexRoute: typeof AdminDashboardCustomersPendingProfilesIndexRoute
  AdminDashboardInventoryEquipmentTypesIndexRoute: typeof AdminDashboardInventoryEquipmentTypesIndexRoute
  AdminDashboardOrdersOrderIdIndexRoute: typeof AdminDashboardOrdersOrderIdIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBranchesNewRoute: AdminDashboardBranchesNewRoute,
  AdminDashboardCatalogNewRoute: AdminDashboardCatalogNewRoute,
  AdminDashboardOrdersNewRoute: AdminDashboardOrdersNewRoute,
  AdminDashboardOwnersOwnerIdRoute: AdminDashboardOwnersOwnerIdRoute,
  AdminDashboardPromotionsNewRoute: AdminDashboardPromotionsNewRoute,
  AdminDashboardCalendarIndexRoute: AdminDashboardCalendarIndexRoute,
  AdminDashboardCatalogIndexRoute: AdminDashboardCatalogIndexRoute,
  AdminDashboardCustomersIndexRoute: AdminDashboardCustomersIndexRoute,
  AdminDashboardOrdersIndexRoute: AdminDashboardOrdersIndexRoute,
  AdminDashboardOwnersIndexRoute: AdminDashboardOwnersIndexRoute,
  AdminDashboardPromotionsIndexRoute: AdminDashboardPromotionsIndexRoute,
  AdminDashboardSettingsIndexRoute: AdminDashboardSettingsIndexRoute,
  AdminDashboardBranchesBranchIdEditRoute:
    AdminDashboardBranchesBranchIdEditRoute,
  AdminDashboardCatalogRentableItemIdEditRoute:
    AdminDashboardCatalogRentableItemIdEditRoute,
  AdminDashboardCatalogPackagesNewRoute: AdminDashboardCatalogPackagesNewRoute,
  AdminDashboardCustomersPendingProfilesCustomerIdRoute:
    AdminDashboardCustomersPendingProfilesCustomerIdRoute,
  AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute:
    AdminDashboardInventoryEquipmentTypesEquipmentTypeIdRoute,
  AdminDashboardPromotionsPromotionIdEditRoute:
    AdminDashboardPromotionsPromotionIdEditRoute,
  AdminDashboardCatalogRentableItemIdIndexRoute:
    AdminDashboardCatalogRentableItemIdIndexRoute,
  AdminDashboardCatalogCategoriesIndexRoute:
    AdminDashboardCatalogCategoriesIndexRoute,
  AdminDashboardCustomersPendingProfilesIndexRoute:
    AdminDashboardCustomersPendingProfilesIndexRoute,
  AdminDashboardInventoryEquipmentTypesIndexRoute:
    AdminDashboardInventoryEquipmentTypesIndexRoute,
  AdminDashboardOrdersOrderIdIndexRoute: AdminDashboardOrdersOrderIdIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminAdminRegisterRoute: typeof AdminAdminRegisterRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminAdminRegisterRoute: AdminAdminRegisterRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiBrandingUploadRoute: ApiBrandingUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  BackendSplatRoute: BackendSplatRoute,
  ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute:
    ApiCustomerProfilesCustomerProfileIdIdentityDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
